// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package egressq

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ApiKey struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	KeyPrefix  string       `json:"key_prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type CapabilityGrant struct {
	AgentID   string         `json:"agent_id"`
	SecretID  string         `json:"secret_id"`
	GrantedBy string         `json:"granted_by"`
	GrantedAt string         `json:"granted_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
	Notes     string         `json:"notes"`
}

type CapabilityLog struct {
	ID          string         `json:"id"`
	AgentID     string         `json:"agent_id"`
	SecretID    sql.NullString `json:"secret_id"`
	SecretName  string         `json:"secret_name"`
	Destination string         `json:"destination"`
	Method      string         `json:"method"`
	Event       string         `json:"event"`
	StatusCode  sql.NullInt64  `json:"status_code"`
	Error       string         `json:"error"`
	Nonce       string         `json:"nonce"`
	IssuedAt    string         `json:"issued_at"`
}

type CapabilitySpentNonce struct {
	Nonce     string `json:"nonce"`
	ExpiresAt string `json:"expires_at"`
}

type Collection struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type CollectionInvitation struct {
	CollectionID string         `json:"collection_id"`
	Email        string         `json:"email"`
	Role         string         `json:"role"`
	InvitedBy    sql.NullString `json:"invited_by"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type CollectionMember struct {
	CollectionID string         `json:"collection_id"`
	UserID       string         `json:"user_id"`
	Role         string         `json:"role"`
	AddedAt      sql.NullTime   `json:"added_at"`
	AcceptedAt   sql.NullTime   `json:"accepted_at"`
	InvitedBy    sql.NullString `json:"invited_by"`
}

type Invitation struct {
	ID         string         `json:"id"`
	Code       string         `json:"code"`
	CodeHash   string         `json:"code_hash"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	Status     string         `json:"status"`
	TargetRole string         `json:"target_role"`
	CreatedBy  sql.NullString `json:"created_by"`
	RedeemedBy sql.NullString `json:"redeemed_by"`
	RedeemedAt sql.NullTime   `json:"redeemed_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type LoginAttempt struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	IpAddress string       `json:"ip_address"`
	Success   int64        `json:"success"`
	CreatedAt sql.NullTime `json:"created_at"`
	Scope     string       `json:"scope"`
}

type NotificationChannel struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	Type              string        `json:"type"`
	Enabled           sql.NullInt64 `json:"enabled"`
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	Events            string        `json:"events"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
}

type ServiceIdentity struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	AllowedSecrets  string         `json:"allowed_secrets"`
	KeyHash         string         `json:"key_hash"`
	KeyPrefix       string         `json:"key_prefix"`
	LastUsedAt      sql.NullTime   `json:"last_used_at"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	RevokedAt       sql.NullTime   `json:"revoked_at"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

type ServiceSecretAudit struct {
	ID                string         `json:"id"`
	ServiceIdentityID sql.NullString `json:"service_identity_id"`
	ServiceName       string         `json:"service_name"`
	Event             string         `json:"event"`
	SecretNames       string         `json:"secret_names"`
	Error             string         `json:"error"`
	RemoteIp          string         `json:"remote_ip"`
	OccurredAt        time.Time      `json:"occurred_at"`
}

type Session struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID                 string         `json:"id"`
	Email              string         `json:"email"`
	PasswordHash       string         `json:"password_hash"`
	Name               sql.NullString `json:"name"`
	Role               string         `json:"role"`
	Disabled           int64          `json:"disabled"`
	TotpSecret         sql.NullString `json:"totp_secret"`
	TotpEnabled        sql.NullInt64  `json:"totp_enabled"`
	TotpRecoveryCodes  sql.NullString `json:"totp_recovery_codes"`
	TotpLastStep       sql.NullInt64  `json:"totp_last_step"`
	SessionsValidAfter int64          `json:"sessions_valid_after"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type VaultEntry struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Url                  sql.NullString `json:"url"`
	Username             sql.NullString `json:"username"`
	EncryptionVersion    sql.NullInt64  `json:"encryption_version"`
	AliasUrl             sql.NullString `json:"alias_url"`
	AutoLogin            int64          `json:"auto_login"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	RotationLog          sql.NullString `json:"rotation_log"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	RotationTargets      sql.NullString `json:"rotation_targets"`
	DestinationPatterns  string         `json:"destination_patterns"`
	InjectionSpec        string         `json:"injection_spec"`
	UrlBidx              string         `json:"url_bidx"`
	AliasUrlBidx         string         `json:"alias_url_bidx"`
	NameBidx             string         `json:"name_bidx"`
	CollectionID         sql.NullString `json:"collection_id"`
	CustomFields         string         `json:"custom_fields"`
	SecretOwnerUserID    string         `json:"secret_owner_user_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}
