// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package egressq

import (
	"context"
)

type Querier interface {
	// EVERY STATEMENT THAT WRITES A HOST-CHOOSING COLUMN OF vault_entries.
	//
	// These used to live in internal/db/queries alongside every other query, which
	// meant sqlc put them on *db.Queries, which meant any handler could call one.
	// Five rounds of the same defect ended the same way: a write path that never
	// asked who was allowed to redirect the secret, sitting next to a table that
	// said the column was dangerous.
	//
	// They generate into internal/vaultegress/internal/egressq. Go's `internal`
	// rule means that package is importable ONLY from inside internal/vaultegress,
	// so the exported wrappers in internal/vaultegress/writes.go, which demand an
	// egressgate.Ticket, are the only way for the rest of the module to reach them.
	// A handler that tries to call one directly does not fail a test, it fails to
	// compile.
	//
	// ADD A NEW ONE HERE, not in internal/db/queries, whenever the statement writes
	// destination_patterns, provider, provider_meta or rotation_targets, or any new
	// column classified egressChoosesHost. TestNoStatementOutsideTheEgressPackage-
	// WritesAHostChoosingColumn proves that rule against the real SQLite engine
	// rather than against a regular expression, so putting one in the wrong file is
	// caught rather than merely discouraged.
	CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) error
	// Seeds the capability-bridge columns from the provider defaults at
	// enrollment time. Only fills untouched rows so explicit per-entry
	// patterns are never overwritten.
	SeedVaultEntryCapabilityDefaults(ctx context.Context, arg SeedVaultEntryCapabilityDefaultsParams) error
	// The capability ceiling: which hosts/paths an agent token minted for this
	// secret may ever reach. Until this existed the column had exactly one writer
	// (the provider preset seed), so a secret created without a recognised provider
	// could never mint a capability token at all and the MCP feature was unusable.
	UpdateVaultEntryDestinationPatterns(ctx context.Context, arg UpdateVaultEntryDestinationPatternsParams) error
	UpdateVaultEntryProvider(ctx context.Context, arg UpdateVaultEntryProviderParams) error
	UpdateVaultEntryProviderMeta(ctx context.Context, arg UpdateVaultEntryProviderMetaParams) error
	UpdateVaultEntryRotationTargets(ctx context.Context, arg UpdateVaultEntryRotationTargetsParams) error
}

var _ Querier = (*Queries)(nil)
