// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_egress.sql

package egressq

import (
	"context"
	"database/sql"
)

const createVaultEntry = `-- name: CreateVaultEntry :exec

INSERT INTO vault_entries (id, user_id, secret_owner_user_id, name, encrypted_value, nonce, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, provider, provider_meta, auto_rotate, url_bidx, alias_url_bidx, name_bidx, encryption_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 2)
`

type CreateVaultEntryParams struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	SecretOwnerUserID    string         `json:"secret_owner_user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	UrlBidx              string         `json:"url_bidx"`
	AliasUrlBidx         string         `json:"alias_url_bidx"`
	NameBidx             string         `json:"name_bidx"`
}

// EVERY STATEMENT THAT WRITES A HOST-CHOOSING COLUMN OF vault_entries.
//
// These used to live in internal/db/queries alongside every other query, which
// meant sqlc put them on *db.Queries, which meant any handler could call one.
// Five rounds of the same defect ended the same way: a write path that never
// asked who was allowed to redirect the secret, sitting next to a table that
// said the column was dangerous.
//
// They generate into internal/vaultegress/internal/egressq. Go's `internal`
// rule means that package is importable ONLY from inside internal/vaultegress,
// so the exported wrappers in internal/vaultegress/writes.go, which demand an
// egressgate.Ticket, are the only way for the rest of the module to reach them.
// A handler that tries to call one directly does not fail a test, it fails to
// compile.
//
// ADD A NEW ONE HERE, not in internal/db/queries, whenever the statement writes
// destination_patterns, provider, provider_meta or rotation_targets, or any new
// column classified egressChoosesHost. TestNoStatementOutsideTheEgressPackage-
// WritesAHostChoosingColumn proves that rule against the real SQLite engine
// rather than against a regular expression, so putting one in the wrong file is
// caught rather than merely discouraged.
func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, createVaultEntry,
		arg.ID,
		arg.UserID,
		arg.SecretOwnerUserID,
		arg.Name,
		arg.EncryptedValue,
		arg.Nonce,
		arg.Url,
		arg.AliasUrl,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.AutoLogin,
		arg.RotationIntervalDays,
		arg.ExpiresAt,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.UrlBidx,
		arg.AliasUrlBidx,
		arg.NameBidx,
	)
	return err
}

const rekeyVaultEntry = `-- name: RekeyVaultEntry :exec
UPDATE vault_entries
SET encrypted_value = ?, nonce = ?, encryption_version = ?,
    name = ?, url = ?, alias_url = ?, username = ?, category = ?, notes = ?,
    provider_meta = ?, rotation_targets = ?, custom_fields = ?,
    url_bidx = ?, alias_url_bidx = ?, name_bidx = ?
WHERE id = ?
`

type RekeyVaultEntryParams struct {
	EncryptedValue    []byte         `json:"encrypted_value"`
	Nonce             []byte         `json:"nonce"`
	EncryptionVersion sql.NullInt64  `json:"encryption_version"`
	Name              string         `json:"name"`
	Url               sql.NullString `json:"url"`
	AliasUrl          sql.NullString `json:"alias_url"`
	Username          sql.NullString `json:"username"`
	Category          sql.NullString `json:"category"`
	Notes             sql.NullString `json:"notes"`
	ProviderMeta      sql.NullString `json:"provider_meta"`
	RotationTargets   sql.NullString `json:"rotation_targets"`
	CustomFields      string         `json:"custom_fields"`
	UrlBidx           string         `json:"url_bidx"`
	AliasUrlBidx      string         `json:"alias_url_bidx"`
	NameBidx          string         `json:"name_bidx"`
	ID                string         `json:"id"`
}

// Writes every keyed column of one entry at once, for the master-key sweep.
//
// One statement rather than per-column updates on purpose: a row must never be
// half-converted, with (say) the value on the new key and notes still on the old
// one. The sweep also runs inside a transaction, so this is belt and braces, but
// the single statement is what makes the invariant local to the row.
//
// It lives in THIS package because it assigns provider_meta and
// rotation_targets. A re-encryption is not a redirection, but "it does not
// change the destinations" is a property of the caller, not of the statement,
// and this package exists precisely because that distinction cannot be enforced
// by reading SQL. So it takes a ticket like every other host-choosing write, and
// vaultegress.RekeyEntry is the only way to reach it.
//
// updated_at is deliberately NOT touched. Re-encryption is not a user edit, and
// bumping it would make every entry look freshly modified in the UI right after
// an incident, which is the worst possible moment to lose that signal.
func (q *Queries) RekeyVaultEntry(ctx context.Context, arg RekeyVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, rekeyVaultEntry,
		arg.EncryptedValue,
		arg.Nonce,
		arg.EncryptionVersion,
		arg.Name,
		arg.Url,
		arg.AliasUrl,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.ProviderMeta,
		arg.RotationTargets,
		arg.CustomFields,
		arg.UrlBidx,
		arg.AliasUrlBidx,
		arg.NameBidx,
		arg.ID,
	)
	return err
}

const seedVaultEntryCapabilityDefaults = `-- name: SeedVaultEntryCapabilityDefaults :exec
UPDATE vault_entries
SET destination_patterns = ?, injection_spec = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND destination_patterns = '[]' AND injection_spec = '{}'
`

type SeedVaultEntryCapabilityDefaultsParams struct {
	DestinationPatterns string `json:"destination_patterns"`
	InjectionSpec       string `json:"injection_spec"`
	ID                  string `json:"id"`
}

// Seeds the capability-bridge columns from the provider defaults at
// enrollment time. Only fills untouched rows so explicit per-entry
// patterns are never overwritten.
func (q *Queries) SeedVaultEntryCapabilityDefaults(ctx context.Context, arg SeedVaultEntryCapabilityDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, seedVaultEntryCapabilityDefaults, arg.DestinationPatterns, arg.InjectionSpec, arg.ID)
	return err
}

const transferVaultEntrySecretOwner = `-- name: TransferVaultEntrySecretOwner :execresult
UPDATE vault_entries SET user_id = ?, secret_owner_user_id = ?, name_bidx = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type TransferVaultEntrySecretOwnerParams struct {
	UserID            string `json:"user_id"`
	SecretOwnerUserID string `json:"secret_owner_user_id"`
	NameBidx          string `json:"name_bidx"`
	ID                string `json:"id"`
}

// THE ONLY STATEMENT IN THE MODULE THAT MOVES secret_owner_user_id AFTER
// CREATION, and it lives here for the same reason the host-choosing writes do:
// so that "change whose authority governs this plaintext" is not something a
// handler can express.
//
// It writes BOTH columns, deliberately. A transfer that moved the exit's owner
// and left the custodian behind would put UNIQUE(user_id, name) in one person's
// namespace and the widening right in another's, which is the split this column
// exists to make impossible to create by accident.
//
// Its one caller is the hard-delete offboarding path: an instance admin deleting
// a user re-owns the entries that person created inside shared collections, so
// the team keeps them. An instance admin already holds the widening right on
// every entry (grantFor row 3), so this hands them nothing they did not have,
// and the activity log names the transfer.
//
// name_bidx MOVES WITH user_id, and this statement is why it has to.
//
// 00040 encrypted vault_entries.name, which made the inline UNIQUE(user_id, name)
// vacuous on purpose (a fresh nonce per seal means two equal names no longer
// produce equal ciphertext) and moved per-user name uniqueness to the partial
// unique index over name_bidx. That token is an HMAC keyed by the CUSTODIAN, so
// an UPDATE that changes user_id and leaves name_bidx alone leaves the row
// indexed under the PREVIOUS owner: uniqueness stops being enforced for it, and
// the new owner can silently end up holding two entries with the same name.
//
// It also broke the caller's collision handling. Offboarding renames an incoming
// entry when the new owner already has one by that name, and it detected that
// case by catching the UNIQUE constraint error. After 00040 the constraint no
// longer fired, so the rename branch went dead and the duplicates it existed to
// prevent started landing instead.
func (q *Queries) TransferVaultEntrySecretOwner(ctx context.Context, arg TransferVaultEntrySecretOwnerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, transferVaultEntrySecretOwner,
		arg.UserID,
		arg.SecretOwnerUserID,
		arg.NameBidx,
		arg.ID,
	)
}

const updateVaultEntryDestinationPatterns = `-- name: UpdateVaultEntryDestinationPatterns :exec
UPDATE vault_entries SET destination_patterns = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryDestinationPatternsParams struct {
	DestinationPatterns string `json:"destination_patterns"`
	ID                  string `json:"id"`
}

// The capability ceiling: which hosts/paths an agent token minted for this
// secret may ever reach. Until this existed the column had exactly one writer
// (the provider preset seed), so a secret created without a recognised provider
// could never mint a capability token at all and the MCP feature was unusable.
func (q *Queries) UpdateVaultEntryDestinationPatterns(ctx context.Context, arg UpdateVaultEntryDestinationPatternsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryDestinationPatterns, arg.DestinationPatterns, arg.ID)
	return err
}

const updateVaultEntryProvider = `-- name: UpdateVaultEntryProvider :exec
UPDATE vault_entries SET provider = ?, provider_meta = ?, auto_rotate = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderParams struct {
	Provider     sql.NullString `json:"provider"`
	ProviderMeta sql.NullString `json:"provider_meta"`
	AutoRotate   sql.NullInt64  `json:"auto_rotate"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryProvider(ctx context.Context, arg UpdateVaultEntryProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProvider,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.ID,
	)
	return err
}

const updateVaultEntryProviderMeta = `-- name: UpdateVaultEntryProviderMeta :exec
UPDATE vault_entries SET provider_meta = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderMetaParams struct {
	ProviderMeta sql.NullString `json:"provider_meta"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryProviderMeta(ctx context.Context, arg UpdateVaultEntryProviderMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProviderMeta, arg.ProviderMeta, arg.ID)
	return err
}

const updateVaultEntryRotationTargets = `-- name: UpdateVaultEntryRotationTargets :exec
UPDATE vault_entries SET rotation_targets = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationTargetsParams struct {
	RotationTargets sql.NullString `json:"rotation_targets"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationTargets(ctx context.Context, arg UpdateVaultEntryRotationTargetsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationTargets, arg.RotationTargets, arg.ID)
	return err
}
