// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_egress.sql

package egressq

import (
	"context"
	"database/sql"
)

const createVaultEntry = `-- name: CreateVaultEntry :exec

INSERT INTO vault_entries (id, user_id, name, encrypted_value, nonce, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, provider, provider_meta, auto_rotate, url_bidx, alias_url_bidx, encryption_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 2)
`

type CreateVaultEntryParams struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	UrlBidx              string         `json:"url_bidx"`
	AliasUrlBidx         string         `json:"alias_url_bidx"`
}

// EVERY STATEMENT THAT WRITES A HOST-CHOOSING COLUMN OF vault_entries.
//
// These used to live in internal/db/queries alongside every other query, which
// meant sqlc put them on *db.Queries, which meant any handler could call one.
// Five rounds of the same defect ended the same way: a write path that never
// asked who was allowed to redirect the secret, sitting next to a table that
// said the column was dangerous.
//
// They generate into internal/vaultegress/internal/egressq. Go's `internal`
// rule means that package is importable ONLY from inside internal/vaultegress,
// so the exported wrappers in internal/vaultegress/writes.go, which demand an
// egressgate.Ticket, are the only way for the rest of the module to reach them.
// A handler that tries to call one directly does not fail a test, it fails to
// compile.
//
// ADD A NEW ONE HERE, not in internal/db/queries, whenever the statement writes
// destination_patterns, provider, provider_meta or rotation_targets, or any new
// column classified egressChoosesHost. TestNoStatementOutsideTheEgressPackage-
// WritesAHostChoosingColumn proves that rule against the real SQLite engine
// rather than against a regular expression, so putting one in the wrong file is
// caught rather than merely discouraged.
func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, createVaultEntry,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedValue,
		arg.Nonce,
		arg.Url,
		arg.AliasUrl,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.AutoLogin,
		arg.RotationIntervalDays,
		arg.ExpiresAt,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.UrlBidx,
		arg.AliasUrlBidx,
	)
	return err
}

const seedVaultEntryCapabilityDefaults = `-- name: SeedVaultEntryCapabilityDefaults :exec
UPDATE vault_entries
SET destination_patterns = ?, injection_spec = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND destination_patterns = '[]' AND injection_spec = '{}'
`

type SeedVaultEntryCapabilityDefaultsParams struct {
	DestinationPatterns string `json:"destination_patterns"`
	InjectionSpec       string `json:"injection_spec"`
	ID                  string `json:"id"`
}

// Seeds the capability-bridge columns from the provider defaults at
// enrollment time. Only fills untouched rows so explicit per-entry
// patterns are never overwritten.
func (q *Queries) SeedVaultEntryCapabilityDefaults(ctx context.Context, arg SeedVaultEntryCapabilityDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, seedVaultEntryCapabilityDefaults, arg.DestinationPatterns, arg.InjectionSpec, arg.ID)
	return err
}

const updateVaultEntryDestinationPatterns = `-- name: UpdateVaultEntryDestinationPatterns :exec
UPDATE vault_entries SET destination_patterns = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryDestinationPatternsParams struct {
	DestinationPatterns string `json:"destination_patterns"`
	ID                  string `json:"id"`
}

// The capability ceiling: which hosts/paths an agent token minted for this
// secret may ever reach. Until this existed the column had exactly one writer
// (the provider preset seed), so a secret created without a recognised provider
// could never mint a capability token at all and the MCP feature was unusable.
func (q *Queries) UpdateVaultEntryDestinationPatterns(ctx context.Context, arg UpdateVaultEntryDestinationPatternsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryDestinationPatterns, arg.DestinationPatterns, arg.ID)
	return err
}

const updateVaultEntryProvider = `-- name: UpdateVaultEntryProvider :exec
UPDATE vault_entries SET provider = ?, provider_meta = ?, auto_rotate = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderParams struct {
	Provider     sql.NullString `json:"provider"`
	ProviderMeta sql.NullString `json:"provider_meta"`
	AutoRotate   sql.NullInt64  `json:"auto_rotate"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryProvider(ctx context.Context, arg UpdateVaultEntryProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProvider,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.ID,
	)
	return err
}

const updateVaultEntryProviderMeta = `-- name: UpdateVaultEntryProviderMeta :exec
UPDATE vault_entries SET provider_meta = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderMetaParams struct {
	ProviderMeta sql.NullString `json:"provider_meta"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryProviderMeta(ctx context.Context, arg UpdateVaultEntryProviderMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProviderMeta, arg.ProviderMeta, arg.ID)
	return err
}

const updateVaultEntryRotationTargets = `-- name: UpdateVaultEntryRotationTargets :exec
UPDATE vault_entries SET rotation_targets = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationTargetsParams struct {
	RotationTargets sql.NullString `json:"rotation_targets"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationTargets(ctx context.Context, arg UpdateVaultEntryRotationTargetsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationTargets, arg.RotationTargets, arg.ID)
	return err
}
