// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"database/sql"
)

const countActivityEntries = `-- name: CountActivityEntries :one
SELECT COUNT(*) FROM activity_log
`

func (q *Queries) CountActivityEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityEntriesByAction = `-- name: CountActivityEntriesByAction :one
SELECT COUNT(*) FROM activity_log WHERE action = ?
`

func (q *Queries) CountActivityEntriesByAction(ctx context.Context, action string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityEntriesByAction, action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityEntriesByActionPrefix = `-- name: CountActivityEntriesByActionPrefix :one
SELECT COUNT(*) FROM activity_log WHERE action LIKE ? ESCAPE '\'
`

// Backs the "vault.*" style category filters. The UI has always offered them,
// but the only filter query was an exact match, so every wildcard option
// returned zero rows and looked like "nothing ever happened".
// The caller passes the prefix WITHOUT the star (e.g. "vault."), and escapes
// any LIKE metacharacters in it.
func (q *Queries) CountActivityEntriesByActionPrefix(ctx context.Context, action string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityEntriesByActionPrefix, action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityEntriesByUser = `-- name: CountActivityEntriesByUser :one
SELECT COUNT(*) FROM activity_log WHERE user_id = ?
`

func (q *Queries) CountActivityEntriesByUser(ctx context.Context, userID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityEntriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityEntriesFiltered = `-- name: CountActivityEntriesFiltered :one
SELECT COUNT(*) FROM activity_log a
WHERE (CAST(?1 AS TEXT) = '' OR a.user_id = ?1)
  AND (
        (CAST(?2 AS TEXT) = '' AND CAST(?3 AS TEXT) = '')
     OR (CAST(?3 AS TEXT) != ''
         AND substr(a.action, 1, length(CAST(?3 AS TEXT))) = CAST(?3 AS TEXT))
     OR (CAST(?3 AS TEXT) = '' AND a.action = ?2)
  )
`

type CountActivityEntriesFilteredParams struct {
	UserFilter   string `json:"user_filter"`
	ActionFilter string `json:"action_filter"`
	ActionPrefix string `json:"action_prefix"`
}

func (q *Queries) CountActivityEntriesFiltered(ctx context.Context, arg CountActivityEntriesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityEntriesFiltered, arg.UserFilter, arg.ActionFilter, arg.ActionPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity_log (user_id, action, detail, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	UserID    sql.NullString `json:"user_id"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.UserID,
		arg.Action,
		arg.Detail,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listActivityEntries = `-- name: ListActivityEntries :many
SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListActivityEntriesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListActivityEntriesRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListActivityEntries(ctx context.Context, arg ListActivityEntriesParams) ([]ListActivityEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityEntriesRow{}
	for rows.Next() {
		var i ListActivityEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEntriesByAction = `-- name: ListActivityEntriesByAction :many
SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
WHERE a.action = ?
ORDER BY a.created_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListActivityEntriesByActionParams struct {
	Action string `json:"action"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListActivityEntriesByActionRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListActivityEntriesByAction(ctx context.Context, arg ListActivityEntriesByActionParams) ([]ListActivityEntriesByActionRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEntriesByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityEntriesByActionRow{}
	for rows.Next() {
		var i ListActivityEntriesByActionRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEntriesByActionPrefix = `-- name: ListActivityEntriesByActionPrefix :many
SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
WHERE a.action LIKE ? ESCAPE '\'
ORDER BY a.created_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListActivityEntriesByActionPrefixParams struct {
	Action string `json:"action"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListActivityEntriesByActionPrefixRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// See CountActivityEntriesByActionPrefix. Same ordering as the other list
// queries so paging behaves identically.
func (q *Queries) ListActivityEntriesByActionPrefix(ctx context.Context, arg ListActivityEntriesByActionPrefixParams) ([]ListActivityEntriesByActionPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEntriesByActionPrefix, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityEntriesByActionPrefixRow{}
	for rows.Next() {
		var i ListActivityEntriesByActionPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEntriesByUser = `-- name: ListActivityEntriesByUser :many
SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON a.user_id = u.id
WHERE a.user_id = ?
ORDER BY a.created_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListActivityEntriesByUserParams struct {
	UserID sql.NullString `json:"user_id"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

type ListActivityEntriesByUserRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListActivityEntriesByUser(ctx context.Context, arg ListActivityEntriesByUserParams) ([]ListActivityEntriesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityEntriesByUserRow{}
	for rows.Next() {
		var i ListActivityEntriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEntriesFiltered = `-- name: ListActivityEntriesFiltered :many
SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON u.id = a.user_id
WHERE (CAST(? AS TEXT) = '' OR a.user_id = ?)
  AND (
        (CAST(? AS TEXT) = '' AND CAST(? AS TEXT) = '')
     OR (CAST(? AS TEXT) != ''
         AND substr(a.action, 1, length(CAST(? AS TEXT))) = CAST(? AS TEXT))
     OR (CAST(? AS TEXT) = '' AND a.action = ?)
  )
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListActivityEntriesFilteredParams struct {
	UserFilter   string `json:"user_filter"`
	ActionFilter string `json:"action_filter"`
	ActionPrefix string `json:"action_prefix"`
	Limit        int64  `json:"limit"`
	Offset       int64  `json:"offset"`
}

type ListActivityEntriesFilteredRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// One query for all three filters, mirroring ExportActivityEntries.
//
// The list endpoint used a switch whose FIRST arm was "a user is selected", so
// picking a user silently discarded the action filter. The export twin already
// combined them, which meant the table and the CSV of the same view returned
// DIFFERENT rows: for an audit surface, two disagreeing answers is worse than
// one wrong one.
func (q *Queries) ListActivityEntriesFiltered(ctx context.Context, arg ListActivityEntriesFilteredParams) ([]ListActivityEntriesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEntriesFiltered,
		arg.UserFilter,
		arg.ActionFilter,
		arg.ActionPrefix,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityEntriesFilteredRow{}
	for rows.Next() {
		var i ListActivityEntriesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
