// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
)

const createAPIKeyForUser = `-- name: CreateAPIKeyForUser :exec
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyForUserParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateAPIKeyForUser(ctx context.Context, arg CreateAPIKeyForUserParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKeyForUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execresult
DELETE FROM api_keys WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
}

const deleteAPIKeysByUser = `-- name: DeleteAPIKeysByUser :exec
DELETE FROM api_keys WHERE user_id = ?
`

func (q *Queries) DeleteAPIKeysByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeysByUser, userID)
	return err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, key_prefix, last_used_at, expires_at, created_at
FROM api_keys
WHERE user_id = ?
ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	KeyPrefix  string       `json:"key_prefix"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
