// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canonical_email_migration.sql

package db

import (
	"context"
)

const listLoginAttemptEmailIdentitiesForCanonicalMigration = `-- name: ListLoginAttemptEmailIdentitiesForCanonicalMigration :many
SELECT id, email
FROM login_attempts
ORDER BY id
`

type ListLoginAttemptEmailIdentitiesForCanonicalMigrationRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

// Migration 00046 must preserve every attempt row while bringing its lockout
// key onto the same canonical representation as account login lookup.
func (q *Queries) ListLoginAttemptEmailIdentitiesForCanonicalMigration(ctx context.Context) ([]ListLoginAttemptEmailIdentitiesForCanonicalMigrationRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoginAttemptEmailIdentitiesForCanonicalMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoginAttemptEmailIdentitiesForCanonicalMigrationRow{}
	for rows.Next() {
		var i ListLoginAttemptEmailIdentitiesForCanonicalMigrationRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoginAttemptEmailForCanonicalMigration = `-- name: UpdateLoginAttemptEmailForCanonicalMigration :exec
UPDATE login_attempts
SET email = ?1
WHERE id = ?2
`

type UpdateLoginAttemptEmailForCanonicalMigrationParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateLoginAttemptEmailForCanonicalMigration(ctx context.Context, arg UpdateLoginAttemptEmailForCanonicalMigrationParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginAttemptEmailForCanonicalMigration, arg.Email, arg.ID)
	return err
}
