// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability.sql

package db

import (
	"context"
	"database/sql"
)

const countCapabilityLog = `-- name: CountCapabilityLog :one
SELECT COUNT(*) FROM capability_log
WHERE (CAST(?1 AS TEXT) = '' OR agent_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR event = ?2)
  AND (CAST(?3 AS TEXT) = '' OR secret_id = ?3)
`

type CountCapabilityLogParams struct {
	AgentFilter  string `json:"agent_filter"`
	EventFilter  string `json:"event_filter"`
	SecretFilter string `json:"secret_filter"`
}

// The same WHERE as ListCapabilityLog. If they ever drift, the pager reports a
// total the table cannot show.
func (q *Queries) CountCapabilityLog(ctx context.Context, arg CountCapabilityLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCapabilityLog, arg.AgentFilter, arg.EventFilter, arg.SecretFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCapabilityLog = `-- name: ListCapabilityLog :many

SELECT id, agent_id, secret_id, secret_name, destination, method, event,
       status_code, error, issued_at
FROM capability_log
WHERE (CAST(?1 AS TEXT) = '' OR agent_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR event = ?2)
  AND (CAST(?3 AS TEXT) = '' OR secret_id = ?3)
ORDER BY issued_at DESC, id DESC
LIMIT ?5 OFFSET ?4
`

type ListCapabilityLogParams struct {
	AgentFilter  string `json:"agent_filter"`
	EventFilter  string `json:"event_filter"`
	SecretFilter string `json:"secret_filter"`
	Off          int64  `json:"off"`
	Lim          int64  `json:"lim"`
}

type ListCapabilityLogRow struct {
	ID          string         `json:"id"`
	AgentID     string         `json:"agent_id"`
	SecretID    sql.NullString `json:"secret_id"`
	SecretName  string         `json:"secret_name"`
	Destination string         `json:"destination"`
	Method      string         `json:"method"`
	Event       string         `json:"event"`
	StatusCode  sql.NullInt64  `json:"status_code"`
	Error       string         `json:"error"`
	IssuedAt    string         `json:"issued_at"`
}

// ============================================================================
// Reading the credential access trail
// ============================================================================
//
// capability_log has recorded every capability token issued, spent and denied
// since 00020, and until now NOTHING read it. No query, no route, no page. For a
// product whose pitch is that an agent spends a credential it never sees, "which
// agent spent which secret, when, and to where" is not a diagnostic detail, it is
// the receipt the whole design exists to produce, and it was write-only.
//
// 00039 made the table append-only and audit_name_crypto.go sealed secret_name
// under the audit DEK, so the rows are now both immutable and confidential. Those
// two passes protected a trail nobody could look at. This is the half that makes
// them worth having.
// Filters compose, deliberately, in ONE statement.
//
// ListActivityEntriesFiltered's own comment records what the alternative cost:
// its first cut was a switch whose leading arm won, so choosing a user silently
// discarded the action filter and the table and its export disagreed. On an audit
// surface two different answers to the same question is worse than one wrong one,
// so every filter is ANDed here and the count twin below shares the predicate
// verbatim.
func (q *Queries) ListCapabilityLog(ctx context.Context, arg ListCapabilityLogParams) ([]ListCapabilityLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityLog,
		arg.AgentFilter,
		arg.EventFilter,
		arg.SecretFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCapabilityLogRow{}
	for rows.Next() {
		var i ListCapabilityLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SecretID,
			&i.SecretName,
			&i.Destination,
			&i.Method,
			&i.Event,
			&i.StatusCode,
			&i.Error,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilityLogAgents = `-- name: ListCapabilityLogAgents :many
SELECT DISTINCT agent_id FROM capability_log ORDER BY agent_id
`

// The distinct agents that appear in the trail, so the filter is a CHOSEN value
// rather than a typed one. An agent id is an opaque token the operator never
// memorises; a free-text box over it returns nothing and reads as "no activity".
func (q *Queries) ListCapabilityLogAgents(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityLogAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var agent_id string
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
