// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"
	"database/sql"
)

const acceptCollectionInvite = `-- name: AcceptCollectionInvite :execresult
UPDATE collection_members SET accepted_at = CURRENT_TIMESTAMP
WHERE collection_id = ? AND user_id = ? AND accepted_at IS NULL
`

type AcceptCollectionInviteParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

func (q *Queries) AcceptCollectionInvite(ctx context.Context, arg AcceptCollectionInviteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acceptCollectionInvite, arg.CollectionID, arg.UserID)
}

const addCollectionMember = `-- name: AddCollectionMember :exec

INSERT INTO collection_members (collection_id, user_id, role, accepted_at, invited_by) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(collection_id, user_id) DO UPDATE SET
  role = excluded.role,
  invited_by = CASE WHEN collection_members.accepted_at IS NULL THEN excluded.invited_by ELSE collection_members.invited_by END
`

type AddCollectionMemberParams struct {
	CollectionID string         `json:"collection_id"`
	UserID       string         `json:"user_id"`
	Role         string         `json:"role"`
	AcceptedAt   sql.NullTime   `json:"accepted_at"`
	InvitedBy    sql.NullString `json:"invited_by"`
}

// ============================================================================
// Membership
// ============================================================================
// accepted_at is passed explicitly: NULL for an invitation another user must
// accept, set for a self-membership (the creator of a collection). On conflict
// only the role changes, so re-inviting never silently re-grants access and a
// role change never revokes an existing acceptance.
//
// invited_by records who actually SENT this invitation, which the consent card
// shows. On conflict it is only rewritten while the row is still pending: a role
// change on an already-accepted member must not rewrite the history of who
// brought them in.
func (q *Queries) AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error {
	_, err := q.db.ExecContext(ctx, addCollectionMember,
		arg.CollectionID,
		arg.UserID,
		arg.Role,
		arg.AcceptedAt,
		arg.InvitedBy,
	)
	return err
}

const countAccessibleVaultEntries = `-- name: CountAccessibleVaultEntries :one
WITH accessible AS (
  SELECT e.id FROM vault_entries e
  WHERE EXISTS (SELECT 1 FROM users u WHERE u.id = ? AND u.disabled = 0)
    AND ((e.collection_id IS NULL AND e.user_id = ?)
     OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL))
  LIMIT ?4
), accessible_rows AS (
  SELECT e.id, e.collection_id, e.encrypted_value, e.name, e.url,
         e.alias_url, e.username, e.category, e.notes, e.provider
  FROM vault_entries e
  WHERE e.id IN (SELECT id FROM accessible)
), entry_stats AS (
  SELECT COUNT(*) AS entry_count,
    COALESCE(SUM(
      length(CAST(e.id AS BLOB)) +
      length(CAST(COALESCE(e.collection_id, '') AS BLOB)) +
      MAX(length(e.encrypted_value) - 16, 0) +
      CASE WHEN substr(e.name, 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.name) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(e.name AS BLOB)) END +
      CASE WHEN substr(COALESCE(e.url, ''), 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.url) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(COALESCE(e.url, '') AS BLOB)) END +
      CASE WHEN substr(COALESCE(e.alias_url, ''), 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.alias_url) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(COALESCE(e.alias_url, '') AS BLOB)) END +
      CASE WHEN substr(COALESCE(e.username, ''), 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.username) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(COALESCE(e.username, '') AS BLOB)) END +
      CASE WHEN substr(COALESCE(e.category, ''), 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.category) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(COALESCE(e.category, '') AS BLOB)) END +
      CASE WHEN substr(COALESCE(e.notes, ''), 1, 7) = 'enc:v1:'
        THEN MAX(((length(e.notes) - 7) / 4) * 3 - 30, 0)
        ELSE length(CAST(COALESCE(e.notes, '') AS BLOB)) END +
      length(CAST(COALESCE(e.provider, '') AS BLOB))
    ), 0) AS minimum_portable_bytes
  FROM accessible_rows e
), collection_stats AS (
  SELECT COALESCE(SUM(
    length(CAST(c.id AS BLOB)) +
    length(CAST(c.name AS BLOB)) +
    length(CAST(COALESCE(c.description, '') AS BLOB))
  ), 0) AS minimum_portable_bytes
  FROM collections c
  WHERE c.id IN (
    SELECT DISTINCT collection_id FROM accessible_rows WHERE collection_id IS NOT NULL
  )
)
SELECT entry_stats.entry_count AS entry_count,
       entry_stats.minimum_portable_bytes + collection_stats.minimum_portable_bytes AS minimum_portable_bytes
FROM entry_stats CROSS JOIN collection_stats
`

type CountAccessibleVaultEntriesParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
	MaxRows  int64  `json:"max_rows"`
}

type CountAccessibleVaultEntriesRow struct {
	EntryCount           int64 `json:"entry_count"`
	MinimumPortableBytes int64 `json:"minimum_portable_bytes"`
}

// Export preflight twin of ListAccessibleVaultEntries. Keep the disabled-user
// and accepted-membership predicate byte-identical so the cheap count never
// promises a bulk reveal whose row query has a different scope. The caller
// passes the first disallowed count (currently 5,001), so this preflight cannot
// scan an attacker-sized vault just to learn that it is over the export cap.
//
// minimum_portable_bytes is deliberately a LOWER bound, not an estimate. For
// the entry value AES-GCM adds exactly a 16-byte tag. A sealed metadata column
// is enc:v1: + base64(nonce || ciphertext); base64 can carry at most two padding
// bytes, so floor(encoded/4)*3 - 30 is no greater than its plaintext byte count
// (12-byte nonce + 16-byte tag + at most 2 padding bytes). JSON never represents
// a string in fewer bytes than its UTF-8 input. Fields export may redact or
// reserialize smaller (provider_meta, custom_fields, destination_patterns) are
// intentionally excluded. Therefore a result over the native file ceiling can
// be refused before any row is decrypted without rejecting a document that
// could fit.
func (q *Queries) CountAccessibleVaultEntries(ctx context.Context, arg CountAccessibleVaultEntriesParams) (CountAccessibleVaultEntriesRow, error) {
	row := q.db.QueryRowContext(ctx, countAccessibleVaultEntries,
		arg.ID,
		arg.UserID,
		arg.UserID_2,
		arg.MaxRows,
	)
	var i CountAccessibleVaultEntriesRow
	err := row.Scan(&i.EntryCount, &i.MinimumPortableBytes)
	return i, err
}

const countCollectionEntries = `-- name: CountCollectionEntries :one
SELECT COUNT(*) FROM vault_entries WHERE collection_id = ?
`

func (q *Queries) CountCollectionEntries(ctx context.Context, collectionID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCollectionEntries, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCollectionManagers = `-- name: CountCollectionManagers :one
SELECT COUNT(*) FROM collection_members
WHERE collection_id = ? AND role = 'manager' AND accepted_at IS NOT NULL
`

// Accepted managers only: a pending invitee cannot be the manager that keeps a
// collection from being orphaned.
func (q *Queries) CountCollectionManagers(ctx context.Context, collectionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCollectionManagers, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :exec


INSERT INTO collections (id, name, description, created_by) VALUES (?, ?, ?, ?)
`

type CreateCollectionParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
}

// collections.sql: shared team vaults (collections) + membership, plus the
// collection-aware vault-entry queries that replace the per-user-only lookups so
// a member sees personal entries AND entries in collections they belong to.
// ============================================================================
// Collections CRUD
// ============================================================================
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const deleteCollectionInvitation = `-- name: DeleteCollectionInvitation :execresult
DELETE FROM collection_invitations WHERE collection_id = ? AND email = ?
`

type DeleteCollectionInvitationParams struct {
	CollectionID string `json:"collection_id"`
	Email        string `json:"email"`
}

func (q *Queries) DeleteCollectionInvitation(ctx context.Context, arg DeleteCollectionInvitationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCollectionInvitation, arg.CollectionID, arg.Email)
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, description, created_by, created_at, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionMemberRole = `-- name: GetCollectionMemberRole :one
SELECT role FROM collection_members
WHERE collection_id = ? AND user_id = ? AND accepted_at IS NOT NULL
`

type GetCollectionMemberRoleParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

// Authorization lookup: a PENDING membership returns no row, so it grants
// neither read nor write anywhere entryAccess or canWriteCollection is used.
func (q *Queries) GetCollectionMemberRole(ctx context.Context, arg GetCollectionMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCollectionMemberRole, arg.CollectionID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getCollectionMembership = `-- name: GetCollectionMembership :one
SELECT role, accepted_at FROM collection_members
WHERE collection_id = ? AND user_id = ?
`

type GetCollectionMembershipParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

type GetCollectionMembershipRow struct {
	Role       string       `json:"role"`
	AcceptedAt sql.NullTime `json:"accepted_at"`
}

// EXISTENCE lookup, acceptance-agnostic. Deliberately separate from
// GetCollectionMemberRole: that one is the authorization gate and must keep
// ignoring pending rows, but management operations need to see a pending
// invitation too. RemoveMember used the authorization query as its existence
// check, so rescinding an invitation that had not been accepted 404'd with
// "member not found" and the invite stayed acceptable forever, with no way for
// anyone to withdraw it. Never use this to decide access.
func (q *Queries) GetCollectionMembership(ctx context.Context, arg GetCollectionMembershipParams) (GetCollectionMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getCollectionMembership, arg.CollectionID, arg.UserID)
	var i GetCollectionMembershipRow
	err := row.Scan(&i.Role, &i.AcceptedAt)
	return i, err
}

const getVaultEntryAccess = `-- name: GetVaultEntryAccess :one

SELECT user_id, secret_owner_user_id, collection_id FROM vault_entries WHERE id = ?
`

type GetVaultEntryAccessRow struct {
	UserID            string         `json:"user_id"`
	SecretOwnerUserID string         `json:"secret_owner_user_id"`
	CollectionID      sql.NullString `json:"collection_id"`
}

// ============================================================================
// Collection-aware vault-entry access
// ============================================================================
// Returns the custodian, the SECRET OWNER and the collection of an entry so the
// handler can authorize a single-entry operation (personal: owner-or-admin;
// collection: member role).
//
// Two owner columns, because they answer two questions and conflating them is
// what made round 7's gate decorative on one path:
//
//	user_id               the CUSTODIAN. grantFor's isCreator, the
//	                      UNIQUE(user_id, name) namespace, the listing scope. A
//	                      collection MANAGER moves it to themselves by adopting
//	                      an orphaned entry, which is legitimate and is what
//	                      keeps a rename from being an oracle over a colleague's
//	                      private vault.
//	secret_owner_user_id  the OWNER the EXIT asks about (mayDirectSecretEgress).
//	                      Adoption does not move it, and nothing else in the
//	                      module can: see internal/vaultegress.
func (q *Queries) GetVaultEntryAccess(ctx context.Context, id string) (GetVaultEntryAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryAccess, id)
	var i GetVaultEntryAccessRow
	err := row.Scan(&i.UserID, &i.SecretOwnerUserID, &i.CollectionID)
	return i, err
}

const listAccessibleVaultEntries = `-- name: ListAccessibleVaultEntries :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE EXISTS (SELECT 1 FROM users u WHERE u.id = ? AND u.disabled = 0)
  AND ((e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL))
ORDER BY e.name ASC
`

type ListAccessibleVaultEntriesParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

type ListAccessibleVaultEntriesRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// The disabled-account clause matches grantFor's row 2. Without it, disabling an
// account left the unlock screen returning every shared secret's plaintext to
// it, which is the widest of the offboarding doors because it is bulk rather
// than one entry. Bind params: userID three times.
func (q *Queries) ListAccessibleVaultEntries(ctx context.Context, arg ListAccessibleVaultEntriesParams) ([]ListAccessibleVaultEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntries, arg.ID, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleVaultEntriesRow{}
	for rows.Next() {
		var i ListAccessibleVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVaultEntriesWithSecrets = `-- name: ListAccessibleVaultEntriesWithSecrets :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.custom_fields, e.destination_patterns, e.created_at, e.updated_at, e.encrypted_value, e.nonce
FROM vault_entries e
WHERE EXISTS (SELECT 1 FROM users u WHERE u.id = ? AND u.disabled = 0)
  AND ((e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL))
ORDER BY e.name ASC
`

type ListAccessibleVaultEntriesWithSecretsParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

type ListAccessibleVaultEntriesWithSecretsRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CustomFields         string         `json:"custom_fields"`
	DestinationPatterns  string         `json:"destination_patterns"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
}

// The disabled-account clause matches grantFor's row 2; see
// ListAccessibleVaultEntries above. Bind params: userID three times.
func (q *Queries) ListAccessibleVaultEntriesWithSecrets(ctx context.Context, arg ListAccessibleVaultEntriesWithSecretsParams) ([]ListAccessibleVaultEntriesWithSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntriesWithSecrets, arg.ID, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleVaultEntriesWithSecretsRow{}
	for rows.Next() {
		var i ListAccessibleVaultEntriesWithSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CustomFields,
			&i.DestinationPatterns,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptedValue,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVaultEntryNames = `-- name: ListAccessibleVaultEntryNames :many
SELECT e.name FROM vault_entries e
WHERE (e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL)
`

type ListAccessibleVaultEntryNamesParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

// Names visible to the user (personal + collections) for import conflict checks.
func (q *Queries) ListAccessibleVaultEntryNames(ctx context.Context, arg ListAccessibleVaultEntryNamesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntryNames, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollections = `-- name: ListAllCollections :many
SELECT id, name, description, created_by, created_at, updated_at FROM collections ORDER BY name ASC
`

func (q *Queries) ListAllCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listAllCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionInvitations = `-- name: ListCollectionInvitations :many
SELECT collection_id, email, role, invited_by, created_at FROM collection_invitations
WHERE collection_id = ? ORDER BY email ASC
`

func (q *Queries) ListCollectionInvitations(ctx context.Context, collectionID string) ([]CollectionInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionInvitations, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionInvitation{}
	for rows.Next() {
		var i CollectionInvitation
		if err := rows.Scan(
			&i.CollectionID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionInvitationsForEmail = `-- name: ListCollectionInvitationsForEmail :many
SELECT collection_id, role, invited_by FROM collection_invitations
WHERE email = ? ORDER BY collection_id ASC
`

type ListCollectionInvitationsForEmailRow struct {
	CollectionID string         `json:"collection_id"`
	Role         string         `json:"role"`
	InvitedBy    sql.NullString `json:"invited_by"`
}

// Every seat waiting for one address, read at ACCOUNT CREATION.
//
// Recording the seat by email fixed the enumeration oracle but broke redemption:
// a seat for an address with no account never became a membership, so the
// invitee could not accept it after signing up and the manager stared at a
// pending row that would never resolve. That is the exact client-onboarding flow
// (invite the client, they register, they join) this work exists to enable.
//
// The seat row is deliberately NOT deleted when it is claimed. The seat is what
// ListMembers renders, so removing it would change the pending entry's shape the
// moment the address registered, which is the account-existence answer again by
// another route.
func (q *Queries) ListCollectionInvitationsForEmail(ctx context.Context, email string) ([]ListCollectionInvitationsForEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionInvitationsForEmailRow{}
	for rows.Next() {
		var i ListCollectionInvitationsForEmailRow
		if err := rows.Scan(&i.CollectionID, &i.Role, &i.InvitedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionMembers = `-- name: ListCollectionMembers :many
SELECT cm.user_id, cm.role, cm.added_at, cm.accepted_at, u.email, u.name
FROM collection_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.collection_id = ?
ORDER BY u.email ASC
`

type ListCollectionMembersRow struct {
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	AddedAt    sql.NullTime   `json:"added_at"`
	AcceptedAt sql.NullTime   `json:"accepted_at"`
	Email      string         `json:"email"`
	Name       sql.NullString `json:"name"`
}

func (q *Queries) ListCollectionMembers(ctx context.Context, collectionID string) ([]ListCollectionMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionMembersRow{}
	for rows.Next() {
		var i ListCollectionMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.AddedAt,
			&i.AcceptedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionVaultEntryNamesSample = `-- name: ListCollectionVaultEntryNamesSample :many
SELECT id, name FROM vault_entries WHERE collection_id = ? ORDER BY id ASC LIMIT ?
`

type ListCollectionVaultEntryNamesSampleParams struct {
	CollectionID sql.NullString `json:"collection_id"`
	Limit        int64          `json:"limit"`
}

type ListCollectionVaultEntryNamesSampleRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// A bounded sample of the entries a collection holds, read by DeleteCollection
// right before the FK cascade destroys them, so activity_log can name what was
// lost instead of just noting that something was. Capped by LIMIT (the caller
// passes it) rather than returned in full: a collection with hundreds of
// entries would otherwise write an unbounded blob into the one append-only
// trail this product has, and the exact count from CountCollectionEntries
// already sits beside the sample in the log line for anything past the cap.
//
// ORDER BY id, not name. name is ciphertext since 00040, so ordering by it
// ordered by nonce: WHICH 25 of 30 entries got named in the permanent log was
// random per delete, and re-running the same delete would have named a different
// set. The caller sorts the DECRYPTED names before writing the line, so the log
// still reads alphabetically; only the choice of which rows fall inside the cap
// is made here, and it is now stable.
func (q *Queries) ListCollectionVaultEntryNamesSample(ctx context.Context, arg ListCollectionVaultEntryNamesSampleParams) ([]ListCollectionVaultEntryNamesSampleRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionVaultEntryNamesSample, arg.CollectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionVaultEntryNamesSampleRow{}
	for rows.Next() {
		var i ListCollectionVaultEntryNamesSampleRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsForUser = `-- name: ListCollectionsForUser :many
SELECT c.id, c.name, c.description, c.created_by, c.created_at, c.updated_at, cm.role
FROM collections c
JOIN collection_members cm ON cm.collection_id = c.id
WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL
ORDER BY c.name ASC
`

type ListCollectionsForUserRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Role        string         `json:"role"`
}

// Accepted memberships only. A pending invitation must not surface the
// collection (or its entries) until the invitee opts in.
func (q *Queries) ListCollectionsForUser(ctx context.Context, userID string) ([]ListCollectionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsForUserRow{}
	for rows.Next() {
		var i ListCollectionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCollectionInvitesForUser = `-- name: ListPendingCollectionInvitesForUser :many
SELECT c.id, c.name, c.description, cm.role, cm.added_at, u.email AS invited_by_email
FROM collections c
JOIN collection_members cm ON cm.collection_id = c.id
LEFT JOIN users u ON u.id = cm.invited_by
WHERE cm.user_id = ? AND cm.accepted_at IS NULL
ORDER BY cm.added_at DESC
`

type ListPendingCollectionInvitesForUserRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Role           string         `json:"role"`
	AddedAt        sql.NullTime   `json:"added_at"`
	InvitedByEmail sql.NullString `json:"invited_by_email"`
}

// Invitations awaiting the user's decision. These grant no access.
func (q *Queries) ListPendingCollectionInvitesForUser(ctx context.Context, userID string) ([]ListPendingCollectionInvitesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCollectionInvitesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCollectionInvitesForUserRow{}
	for rows.Next() {
		var i ListPendingCollectionInvitesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.AddedAt,
			&i.InvitedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchAccessibleVaultEntriesByURL = `-- name: MatchAccessibleVaultEntriesByURL :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE EXISTS (SELECT 1 FROM users u WHERE u.id = ? AND u.disabled = 0)
  AND ((e.collection_id IS NULL AND e.user_id = ?)
       OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL))
  AND ((e.url_bidx != '' AND e.url_bidx = ?) OR (e.alias_url_bidx != '' AND e.alias_url_bidx = ?))
ORDER BY e.name ASC
`

type MatchAccessibleVaultEntriesByURLParams struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	UserID_2     string `json:"user_id_2"`
	UrlBidx      string `json:"url_bidx"`
	AliasUrlBidx string `json:"alias_url_bidx"`
}

type MatchAccessibleVaultEntriesByURLRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// The disabled-account clause matches grantFor's row 2. This one feeds
// browser-extension autofill, so a disabled account kept getting entry
// suggestions for collections it had been cut from.
func (q *Queries) MatchAccessibleVaultEntriesByURL(ctx context.Context, arg MatchAccessibleVaultEntriesByURLParams) ([]MatchAccessibleVaultEntriesByURLRow, error) {
	rows, err := q.db.QueryContext(ctx, matchAccessibleVaultEntriesByURL,
		arg.ID,
		arg.UserID,
		arg.UserID_2,
		arg.UrlBidx,
		arg.AliasUrlBidx,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchAccessibleVaultEntriesByURLRow{}
	for rows.Next() {
		var i MatchAccessibleVaultEntriesByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchCollectionVaultEntriesByURL = `-- name: MatchCollectionVaultEntriesByURL :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE e.collection_id = ?
  AND ((e.url_bidx != '' AND e.url_bidx = ?) OR (e.alias_url_bidx != '' AND e.alias_url_bidx = ?))
ORDER BY e.name ASC
`

type MatchCollectionVaultEntriesByURLParams struct {
	CollectionID sql.NullString `json:"collection_id"`
	UrlBidx      string         `json:"url_bidx"`
	AliasUrlBidx string         `json:"alias_url_bidx"`
}

type MatchCollectionVaultEntriesByURLRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// Autofill within one collection the caller has ACCEPTED. Callers must check
// membership before calling; the collection id is the index scope.
func (q *Queries) MatchCollectionVaultEntriesByURL(ctx context.Context, arg MatchCollectionVaultEntriesByURLParams) ([]MatchCollectionVaultEntriesByURLRow, error) {
	rows, err := q.db.QueryContext(ctx, matchCollectionVaultEntriesByURL, arg.CollectionID, arg.UrlBidx, arg.AliasUrlBidx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchCollectionVaultEntriesByURLRow{}
	for rows.Next() {
		var i MatchCollectionVaultEntriesByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchPersonalVaultEntriesByURL = `-- name: MatchPersonalVaultEntriesByURL :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE e.collection_id IS NULL AND e.user_id = ?
  AND ((e.url_bidx != '' AND e.url_bidx = ?) OR (e.alias_url_bidx != '' AND e.alias_url_bidx = ?))
ORDER BY e.name ASC
`

type MatchPersonalVaultEntriesByURLParams struct {
	UserID       string `json:"user_id"`
	UrlBidx      string `json:"url_bidx"`
	AliasUrlBidx string `json:"alias_url_bidx"`
}

type MatchPersonalVaultEntriesByURLRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// Autofill within the caller's PERSONAL scope. The blind index is keyed per
// scope, so a personal entry and a collection entry for the same host produce
// different index values and a stolen database no longer reveals that two users
// hold entries for the same site.
func (q *Queries) MatchPersonalVaultEntriesByURL(ctx context.Context, arg MatchPersonalVaultEntriesByURLParams) ([]MatchPersonalVaultEntriesByURLRow, error) {
	rows, err := q.db.QueryContext(ctx, matchPersonalVaultEntriesByURL, arg.UserID, arg.UrlBidx, arg.AliasUrlBidx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPersonalVaultEntriesByURLRow{}
	for rows.Next() {
		var i MatchPersonalVaultEntriesByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionMember = `-- name: RemoveCollectionMember :execresult
DELETE FROM collection_members WHERE collection_id = ? AND user_id = ?
`

type RemoveCollectionMemberParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

func (q *Queries) RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeCollectionMember, arg.CollectionID, arg.UserID)
}

const restoreNativeImportedCollectionTimestamps = `-- name: RestoreNativeImportedCollectionTimestamps :exec
UPDATE collections SET created_at = ?, updated_at = ? WHERE id = ?
`

type RestoreNativeImportedCollectionTimestampsParams struct {
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        string       `json:"id"`
}

// Native imports create a private copy with a fresh id and fresh authority, but
// retain the source document's content timestamps for portable history.
func (q *Queries) RestoreNativeImportedCollectionTimestamps(ctx context.Context, arg RestoreNativeImportedCollectionTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, restoreNativeImportedCollectionTimestamps, arg.CreatedAt, arg.UpdatedAt, arg.ID)
	return err
}

const setVaultEntryCollection = `-- name: SetVaultEntryCollection :exec
UPDATE vault_entries SET collection_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetVaultEntryCollectionParams struct {
	CollectionID sql.NullString `json:"collection_id"`
	ID           string         `json:"id"`
}

func (q *Queries) SetVaultEntryCollection(ctx context.Context, arg SetVaultEntryCollectionParams) error {
	_, err := q.db.ExecContext(ctx, setVaultEntryCollection, arg.CollectionID, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection, arg.Name, arg.Description, arg.ID)
	return err
}

const upsertCollectionInvitation = `-- name: UpsertCollectionInvitation :exec

INSERT INTO collection_invitations (collection_id, email, role, invited_by) VALUES (?, ?, ?, ?)
ON CONFLICT(collection_id, email) DO UPDATE SET
  role = excluded.role,
  invited_by = excluded.invited_by
`

type UpsertCollectionInvitationParams struct {
	CollectionID string         `json:"collection_id"`
	Email        string         `json:"email"`
	Role         string         `json:"role"`
	InvitedBy    sql.NullString `json:"invited_by"`
}

// ============================================================================
// Pending invitations, keyed by the invited EMAIL
// ============================================================================
//
// These exist so a pending seat is recorded whether or not the address matches
// an account. collection_members can only hold a row for an address that HAS an
// account (user_id is a foreign key), so listing pending memberships told any
// collection manager, including a vault_only user who just created a throwaway
// collection, exactly which addresses are registered. See migration 00033.
// Re-inviting the same address updates the seat's role rather than adding a
// second one, which is also how the members UI sends a role change.
func (q *Queries) UpsertCollectionInvitation(ctx context.Context, arg UpsertCollectionInvitationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCollectionInvitation,
		arg.CollectionID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}
