// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"
	"database/sql"
)

const acceptCollectionInvite = `-- name: AcceptCollectionInvite :execresult
UPDATE collection_members SET accepted_at = CURRENT_TIMESTAMP
WHERE collection_id = ? AND user_id = ? AND accepted_at IS NULL
`

type AcceptCollectionInviteParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

func (q *Queries) AcceptCollectionInvite(ctx context.Context, arg AcceptCollectionInviteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acceptCollectionInvite, arg.CollectionID, arg.UserID)
}

const addCollectionMember = `-- name: AddCollectionMember :exec

INSERT INTO collection_members (collection_id, user_id, role, accepted_at) VALUES (?, ?, ?, ?)
ON CONFLICT(collection_id, user_id) DO UPDATE SET role = excluded.role
`

type AddCollectionMemberParams struct {
	CollectionID string       `json:"collection_id"`
	UserID       string       `json:"user_id"`
	Role         string       `json:"role"`
	AcceptedAt   sql.NullTime `json:"accepted_at"`
}

// ============================================================================
// Membership
// ============================================================================
// accepted_at is passed explicitly: NULL for an invitation another user must
// accept, set for a self-membership (the creator of a collection). On conflict
// only the role changes, so re-inviting never silently re-grants access and a
// role change never revokes an existing acceptance.
func (q *Queries) AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error {
	_, err := q.db.ExecContext(ctx, addCollectionMember,
		arg.CollectionID,
		arg.UserID,
		arg.Role,
		arg.AcceptedAt,
	)
	return err
}

const countCollectionEntries = `-- name: CountCollectionEntries :one
SELECT COUNT(*) FROM vault_entries WHERE collection_id = ?
`

func (q *Queries) CountCollectionEntries(ctx context.Context, collectionID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCollectionEntries, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCollectionManagers = `-- name: CountCollectionManagers :one
SELECT COUNT(*) FROM collection_members
WHERE collection_id = ? AND role = 'manager' AND accepted_at IS NOT NULL
`

// Accepted managers only: a pending invitee cannot be the manager that keeps a
// collection from being orphaned.
func (q *Queries) CountCollectionManagers(ctx context.Context, collectionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCollectionManagers, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :exec


INSERT INTO collections (id, name, description, created_by) VALUES (?, ?, ?, ?)
`

type CreateCollectionParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
}

// collections.sql: shared team vaults (collections) + membership, plus the
// collection-aware vault-entry queries that replace the per-user-only lookups so
// a member sees personal entries AND entries in collections they belong to.
// ============================================================================
// Collections CRUD
// ============================================================================
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, description, created_by, created_at, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionMemberRole = `-- name: GetCollectionMemberRole :one
SELECT role FROM collection_members
WHERE collection_id = ? AND user_id = ? AND accepted_at IS NOT NULL
`

type GetCollectionMemberRoleParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

// Authorization lookup: a PENDING membership returns no row, so it grants
// neither read nor write anywhere entryAccess or canWriteCollection is used.
func (q *Queries) GetCollectionMemberRole(ctx context.Context, arg GetCollectionMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCollectionMemberRole, arg.CollectionID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getVaultEntryAccess = `-- name: GetVaultEntryAccess :one

SELECT user_id, collection_id FROM vault_entries WHERE id = ?
`

type GetVaultEntryAccessRow struct {
	UserID       string         `json:"user_id"`
	CollectionID sql.NullString `json:"collection_id"`
}

// ============================================================================
// Collection-aware vault-entry access
// ============================================================================
// Returns the owner and collection of an entry so the handler can authorize a
// single-entry operation (personal: owner-or-admin; collection: member role).
func (q *Queries) GetVaultEntryAccess(ctx context.Context, id string) (GetVaultEntryAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryAccess, id)
	var i GetVaultEntryAccessRow
	err := row.Scan(&i.UserID, &i.CollectionID)
	return i, err
}

const listAccessibleVaultEntries = `-- name: ListAccessibleVaultEntries :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE (e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL)
ORDER BY e.name ASC
`

type ListAccessibleVaultEntriesParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

type ListAccessibleVaultEntriesRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListAccessibleVaultEntries(ctx context.Context, arg ListAccessibleVaultEntriesParams) ([]ListAccessibleVaultEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntries, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleVaultEntriesRow{}
	for rows.Next() {
		var i ListAccessibleVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVaultEntriesWithSecrets = `-- name: ListAccessibleVaultEntriesWithSecrets :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.custom_fields, e.created_at, e.updated_at, e.encrypted_value, e.nonce
FROM vault_entries e
WHERE (e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL)
ORDER BY e.name ASC
`

type ListAccessibleVaultEntriesWithSecretsParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

type ListAccessibleVaultEntriesWithSecretsRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CustomFields         string         `json:"custom_fields"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
}

func (q *Queries) ListAccessibleVaultEntriesWithSecrets(ctx context.Context, arg ListAccessibleVaultEntriesWithSecretsParams) ([]ListAccessibleVaultEntriesWithSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntriesWithSecrets, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleVaultEntriesWithSecretsRow{}
	for rows.Next() {
		var i ListAccessibleVaultEntriesWithSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptedValue,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleVaultEntryNames = `-- name: ListAccessibleVaultEntryNames :many
SELECT e.name FROM vault_entries e
WHERE (e.collection_id IS NULL AND e.user_id = ?)
   OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL)
`

type ListAccessibleVaultEntryNamesParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

// Names visible to the user (personal + collections) for import conflict checks.
func (q *Queries) ListAccessibleVaultEntryNames(ctx context.Context, arg ListAccessibleVaultEntryNamesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleVaultEntryNames, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollections = `-- name: ListAllCollections :many
SELECT id, name, description, created_by, created_at, updated_at FROM collections ORDER BY name ASC
`

func (q *Queries) ListAllCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listAllCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionMembers = `-- name: ListCollectionMembers :many
SELECT cm.user_id, cm.role, cm.added_at, cm.accepted_at, u.email, u.name
FROM collection_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.collection_id = ?
ORDER BY u.email ASC
`

type ListCollectionMembersRow struct {
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	AddedAt    sql.NullTime   `json:"added_at"`
	AcceptedAt sql.NullTime   `json:"accepted_at"`
	Email      string         `json:"email"`
	Name       sql.NullString `json:"name"`
}

func (q *Queries) ListCollectionMembers(ctx context.Context, collectionID string) ([]ListCollectionMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionMembersRow{}
	for rows.Next() {
		var i ListCollectionMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.AddedAt,
			&i.AcceptedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsForUser = `-- name: ListCollectionsForUser :many
SELECT c.id, c.name, c.description, c.created_by, c.created_at, c.updated_at, cm.role
FROM collections c
JOIN collection_members cm ON cm.collection_id = c.id
WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL
ORDER BY c.name ASC
`

type ListCollectionsForUserRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Role        string         `json:"role"`
}

// Accepted memberships only. A pending invitation must not surface the
// collection (or its entries) until the invitee opts in.
func (q *Queries) ListCollectionsForUser(ctx context.Context, userID string) ([]ListCollectionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsForUserRow{}
	for rows.Next() {
		var i ListCollectionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCollectionInvitesForUser = `-- name: ListPendingCollectionInvitesForUser :many
SELECT c.id, c.name, c.description, cm.role, cm.added_at, u.email AS invited_by_email
FROM collections c
JOIN collection_members cm ON cm.collection_id = c.id
LEFT JOIN users u ON u.id = c.created_by
WHERE cm.user_id = ? AND cm.accepted_at IS NULL
ORDER BY cm.added_at DESC
`

type ListPendingCollectionInvitesForUserRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Role           string         `json:"role"`
	AddedAt        sql.NullTime   `json:"added_at"`
	InvitedByEmail sql.NullString `json:"invited_by_email"`
}

// Invitations awaiting the user's decision. These grant no access.
func (q *Queries) ListPendingCollectionInvitesForUser(ctx context.Context, userID string) ([]ListPendingCollectionInvitesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCollectionInvitesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCollectionInvitesForUserRow{}
	for rows.Next() {
		var i ListPendingCollectionInvitesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.AddedAt,
			&i.InvitedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchAccessibleVaultEntriesByURL = `-- name: MatchAccessibleVaultEntriesByURL :many
SELECT e.id, e.user_id, e.collection_id, e.name, e.url, e.alias_url, e.username, e.category, e.notes, e.auto_login, e.rotation_interval_days, e.expires_at, e.last_rotated_at, e.provider, e.provider_meta, e.auto_rotate, e.last_rotation_error, e.created_at, e.updated_at
FROM vault_entries e
WHERE ((e.collection_id IS NULL AND e.user_id = ?)
       OR e.collection_id IN (SELECT cm.collection_id FROM collection_members cm WHERE cm.user_id = ? AND cm.accepted_at IS NOT NULL))
  AND ((e.url_bidx != '' AND e.url_bidx = ?) OR (e.alias_url_bidx != '' AND e.alias_url_bidx = ?))
ORDER BY e.name ASC
`

type MatchAccessibleVaultEntriesByURLParams struct {
	UserID       string `json:"user_id"`
	UserID_2     string `json:"user_id_2"`
	UrlBidx      string `json:"url_bidx"`
	AliasUrlBidx string `json:"alias_url_bidx"`
}

type MatchAccessibleVaultEntriesByURLRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	CollectionID         sql.NullString `json:"collection_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) MatchAccessibleVaultEntriesByURL(ctx context.Context, arg MatchAccessibleVaultEntriesByURLParams) ([]MatchAccessibleVaultEntriesByURLRow, error) {
	rows, err := q.db.QueryContext(ctx, matchAccessibleVaultEntriesByURL,
		arg.UserID,
		arg.UserID_2,
		arg.UrlBidx,
		arg.AliasUrlBidx,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchAccessibleVaultEntriesByURLRow{}
	for rows.Next() {
		var i MatchAccessibleVaultEntriesByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionMember = `-- name: RemoveCollectionMember :execresult
DELETE FROM collection_members WHERE collection_id = ? AND user_id = ?
`

type RemoveCollectionMemberParams struct {
	CollectionID string `json:"collection_id"`
	UserID       string `json:"user_id"`
}

func (q *Queries) RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeCollectionMember, arg.CollectionID, arg.UserID)
}

const setVaultEntryCollection = `-- name: SetVaultEntryCollection :exec
UPDATE vault_entries SET collection_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetVaultEntryCollectionParams struct {
	CollectionID sql.NullString `json:"collection_id"`
	ID           string         `json:"id"`
}

func (q *Queries) SetVaultEntryCollection(ctx context.Context, arg SetVaultEntryCollectionParams) error {
	_, err := q.db.ExecContext(ctx, setVaultEntryCollection, arg.CollectionID, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection, arg.Name, arg.Description, arg.ID)
	return err
}
