// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package db

import (
	"context"
	"database/sql"
)

const countVaultEntriesForUser = `-- name: CountVaultEntriesForUser :one
SELECT COUNT(*) FROM vault_entries WHERE user_id = ?
`

func (q *Queries) CountVaultEntriesForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVaultEntriesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const exportActivityEntries = `-- name: ExportActivityEntries :many

SELECT a.id, a.user_id, u.email AS user_email, a.action, a.detail,
       a.ip_address, a.user_agent, a.created_at
FROM activity_log a
LEFT JOIN users u ON u.id = a.user_id
WHERE (CAST(?1 AS TEXT) = '' OR a.user_id = ?1)
  AND (
        (CAST(?2 AS TEXT) = '' AND CAST(?3 AS TEXT) = '')
     OR (CAST(?3 AS TEXT) != ''
         AND substr(a.action, 1, length(CAST(?3 AS TEXT))) = CAST(?3 AS TEXT))
     OR (CAST(?3 AS TEXT) = '' AND a.action = ?2)
  )
ORDER BY a.created_at DESC
`

type ExportActivityEntriesParams struct {
	UserFilter   string `json:"user_filter"`
	ActionFilter string `json:"action_filter"`
	ActionPrefix string `json:"action_prefix"`
}

type ExportActivityEntriesRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// Integration-owned queries: activity export and admin user listing with
// vault entry counts. Kept out of the platform-owned query files per the
// CONTRACT.md rule (new queries go in new files).
// action_prefix carries a literal prefix such as "vault." for the UI's "vault.*"
// category options; action_filter carries an exact action. Exactly one is
// non-empty.
//
// The list endpoint learned the prefix form but this export twin did not, so
// selecting a category and clicking Export silently downloaded an EMPTY file:
// the exact-match comparison could never match the literal "vault.*". A filtered
// export that yields nothing, with no error, reads as "there is no such
// activity" rather than "the filter is broken", which is the worst possible
// failure for an audit surface.
func (q *Queries) ExportActivityEntries(ctx context.Context, arg ExportActivityEntriesParams) ([]ExportActivityEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportActivityEntries, arg.UserFilter, arg.ActionFilter, arg.ActionPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportActivityEntriesRow{}
	for rows.Next() {
		var i ExportActivityEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringVaultEntries = `-- name: ListExpiringVaultEntries :many
SELECT id, name, user_id, expires_at
FROM vault_entries
WHERE expires_at IS NOT NULL
  AND expires_at > datetime('now')
  AND expires_at <= datetime('now', '+' || CAST(?1 AS TEXT) || ' days')
ORDER BY expires_at ASC
`

type ListExpiringVaultEntriesRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	UserID    string       `json:"user_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) ListExpiringVaultEntries(ctx context.Context, windowDays string) ([]ListExpiringVaultEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringVaultEntries, windowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringVaultEntriesRow{}
	for rows.Next() {
		var i ListExpiringVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithEntryCount = `-- name: ListUsersWithEntryCount :many
SELECT u.id, u.email, u.name, u.role, u.disabled, u.totp_enabled, u.created_at,
       (SELECT COUNT(*) FROM vault_entries v WHERE v.user_id = u.id) AS entry_count
FROM users u
ORDER BY u.created_at ASC
`

type ListUsersWithEntryCountRow struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Role        string         `json:"role"`
	Disabled    int64          `json:"disabled"`
	TotpEnabled sql.NullInt64  `json:"totp_enabled"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	EntryCount  int64          `json:"entry_count"`
}

func (q *Queries) ListUsersWithEntryCount(ctx context.Context) ([]ListUsersWithEntryCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithEntryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithEntryCountRow{}
	for rows.Next() {
		var i ListUsersWithEntryCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Disabled,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
