// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code, email, name, target_role, created_by, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, code, email, name, status, target_role, expires_at, created_at
`

type CreateInvitationParams struct {
	Code       string         `json:"code"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	TargetRole string         `json:"target_role"`
	CreatedBy  sql.NullString `json:"created_by"`
	ExpiresAt  time.Time      `json:"expires_at"`
}

type CreateInvitationRow struct {
	ID         string       `json:"id"`
	Code       string       `json:"code"`
	Email      string       `json:"email"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	TargetRole string       `json:"target_role"`
	ExpiresAt  time.Time    `json:"expires_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.Code,
		arg.Email,
		arg.Name,
		arg.TargetRole,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.TargetRole,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateInvitedUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Role         string         `json:"role"`
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createInvitedUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deletePendingInvitation = `-- name: DeletePendingInvitation :execresult
DELETE FROM invitations WHERE id = ? AND status = 'pending'
`

func (q *Queries) DeletePendingInvitation(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePendingInvitation, id)
}

const expireStaleInvitations = `-- name: ExpireStaleInvitations :exec
UPDATE invitations SET status = 'expired'
WHERE status = 'pending' AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ExpireStaleInvitations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireStaleInvitations)
	return err
}

const getInvitationForResend = `-- name: GetInvitationForResend :one
SELECT id, code, email, name, status FROM invitations WHERE id = ?
`

type GetInvitationForResendRow struct {
	ID     string `json:"id"`
	Code   string `json:"code"`
	Email  string `json:"email"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) GetInvitationForResend(ctx context.Context, id string) (GetInvitationForResendRow, error) {
	row := q.db.QueryRowContext(ctx, getInvitationForResend, id)
	var i GetInvitationForResendRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getPendingInvitationByCode = `-- name: GetPendingInvitationByCode :one
SELECT id, code, email, name, target_role, expires_at
FROM invitations
WHERE code = ? AND status = 'pending' AND expires_at > CURRENT_TIMESTAMP
`

type GetPendingInvitationByCodeRow struct {
	ID         string    `json:"id"`
	Code       string    `json:"code"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
	TargetRole string    `json:"target_role"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) GetPendingInvitationByCode(ctx context.Context, code string) (GetPendingInvitationByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingInvitationByCode, code)
	var i GetPendingInvitationByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Name,
		&i.TargetRole,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserIDByEmailForInvite = `-- name: GetUserIDByEmailForInvite :one
SELECT id FROM users WHERE email = ?
`

func (q *Queries) GetUserIDByEmailForInvite(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmailForInvite, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, code, email, name, status, target_role, expires_at, created_at
FROM invitations
ORDER BY created_at DESC
`

type ListInvitationsRow struct {
	ID         string       `json:"id"`
	Code       string       `json:"code"`
	Email      string       `json:"email"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	TargetRole string       `json:"target_role"`
	ExpiresAt  time.Time    `json:"expires_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) ListInvitations(ctx context.Context) ([]ListInvitationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.TargetRole,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationRedeemed = `-- name: MarkInvitationRedeemed :exec
UPDATE invitations
SET status = 'redeemed', redeemed_by = ?, redeemed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkInvitationRedeemedParams struct {
	RedeemedBy sql.NullString `json:"redeemed_by"`
	ID         string         `json:"id"`
}

func (q *Queries) MarkInvitationRedeemed(ctx context.Context, arg MarkInvitationRedeemedParams) error {
	_, err := q.db.ExecContext(ctx, markInvitationRedeemed, arg.RedeemedBy, arg.ID)
	return err
}
