// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (name, type, enabled, config, config_nonce, encryption_version, events)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateNotificationChannelParams struct {
	Name              string        `json:"name"`
	Type              string        `json:"type"`
	Enabled           sql.NullInt64 `json:"enabled"`
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	Events            string        `json:"events"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createNotificationChannel,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Config,
		arg.ConfigNonce,
		arg.EncryptionVersion,
		arg.Events,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execresult
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNotificationChannel, id)
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, name, type, enabled, config, config_nonce, encryption_version, events
FROM notification_channels
WHERE id = ?
`

type GetNotificationChannelRow struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	Type              string        `json:"type"`
	Enabled           sql.NullInt64 `json:"enabled"`
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	Events            string        `json:"events"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, id string) (GetNotificationChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannel, id)
	var i GetNotificationChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.ConfigNonce,
		&i.EncryptionVersion,
		&i.Events,
	)
	return i, err
}

const listEnabledNotificationChannels = `-- name: ListEnabledNotificationChannels :many
SELECT id, name, type, config, config_nonce, encryption_version, events
FROM notification_channels
WHERE enabled = 1
`

type ListEnabledNotificationChannelsRow struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	Type              string        `json:"type"`
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	Events            string        `json:"events"`
}

func (q *Queries) ListEnabledNotificationChannels(ctx context.Context) ([]ListEnabledNotificationChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledNotificationChannelsRow{}
	for rows.Next() {
		var i ListEnabledNotificationChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.ConfigNonce,
			&i.EncryptionVersion,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelConfigsForRekey = `-- name: ListNotificationChannelConfigsForRekey :many
SELECT id, name, config, config_nonce, encryption_version
FROM notification_channels
ORDER BY id
`

type ListNotificationChannelConfigsForRekeyRow struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
}

// Channel configs are raw AES-GCM under the vault value key, with the nonce in
// its own column and NO marker in the payload. encryption_version 0 means the
// config was written before at-rest encryption and is plain JSON; the sweep must
// see those rows too so it can report them rather than silently treat a
// cleartext webhook URL (which can carry a bearer token) as already converted.
func (q *Queries) ListNotificationChannelConfigsForRekey(ctx context.Context) ([]ListNotificationChannelConfigsForRekeyRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannelConfigsForRekey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationChannelConfigsForRekeyRow{}
	for rows.Next() {
		var i ListNotificationChannelConfigsForRekeyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.ConfigNonce,
			&i.EncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name, type, enabled, events, encryption_version, created_at, updated_at
FROM notification_channels
ORDER BY created_at ASC
`

type ListNotificationChannelsRow struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	Type              string        `json:"type"`
	Enabled           sql.NullInt64 `json:"enabled"`
	Events            string        `json:"events"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
}

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]ListNotificationChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationChannelsRow{}
	for rows.Next() {
		var i ListNotificationChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Events,
			&i.EncryptionVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rekeyNotificationChannelConfig = `-- name: RekeyNotificationChannelConfig :exec
UPDATE notification_channels
SET config = ?, config_nonce = ?, encryption_version = ?
WHERE id = ?
`

type RekeyNotificationChannelConfigParams struct {
	Config            string        `json:"config"`
	ConfigNonce       []byte        `json:"config_nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
	ID                string        `json:"id"`
}

func (q *Queries) RekeyNotificationChannelConfig(ctx context.Context, arg RekeyNotificationChannelConfigParams) error {
	_, err := q.db.ExecContext(ctx, rekeyNotificationChannelConfig,
		arg.Config,
		arg.ConfigNonce,
		arg.EncryptionVersion,
		arg.ID,
	)
	return err
}

const updateNotificationChannelEnabled = `-- name: UpdateNotificationChannelEnabled :execresult
UPDATE notification_channels
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNotificationChannelEnabledParams struct {
	Enabled sql.NullInt64 `json:"enabled"`
	ID      string        `json:"id"`
}

func (q *Queries) UpdateNotificationChannelEnabled(ctx context.Context, arg UpdateNotificationChannelEnabledParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNotificationChannelEnabled, arg.Enabled, arg.ID)
}
