// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountActivityEntries(ctx context.Context) (int64, error)
	CountActivityEntriesByAction(ctx context.Context, action string) (int64, error)
	CountActivityEntriesByUser(ctx context.Context, userID sql.NullString) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountRecentFailedLoginAttemptsByEmail(ctx context.Context, email string) (int64, error)
	CountRecentFailedLoginAttemptsByIP(ctx context.Context, ipAddress string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVaultEntriesForUser(ctx context.Context, userID string) (int64, error)
	// vault.sql: Secrets vault queries - CRUD, encryption migration, unlock,
	// per-field updates, rotation, URL matching, reference resolution, import.
	// Source: internal/handlers/vault.go, internal/handlers/vault_import.go
	// Copied verbatim from dockyard so generated method names stay identical.
	// ============================================================================
	// Encryption migration (v1 SHA-256 -> v2 PBKDF2)
	// ============================================================================
	CountVaultEntriesV1(ctx context.Context) (int64, error)
	CreateAPIKeyForUser(ctx context.Context, arg CreateAPIKeyForUserParams) error
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (string, error)
	CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (string, error)
	CreateServiceIdentity(ctx context.Context, arg CreateServiceIdentityParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ============================================================================
	// Create entry
	// ============================================================================
	CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) error
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (sql.Result, error)
	DeleteAPIKeysByUser(ctx context.Context, userID string) error
	DeleteNotificationChannel(ctx context.Context, id string) (sql.Result, error)
	DeletePendingInvitation(ctx context.Context, id string) (sql.Result, error)
	DeleteServiceIdentity(ctx context.Context, id string) (sql.Result, error)
	DeleteUser(ctx context.Context, id string) (sql.Result, error)
	DeleteVaultEntry(ctx context.Context, id string) (sql.Result, error)
	DisableTOTP(ctx context.Context, id string) error
	EnableTOTP(ctx context.Context, arg EnableTOTPParams) error
	ExpireStaleInvitations(ctx context.Context) error
	// Integration-owned queries: activity export and admin user listing with
	// vault entry counts. Kept out of the platform-owned query files per the
	// CONTRACT.md rule (new queries go in new files).
	ExportActivityEntries(ctx context.Context, arg ExportActivityEntriesParams) ([]ExportActivityEntriesRow, error)
	GetInvitationForResend(ctx context.Context, id string) (GetInvitationForResendRow, error)
	GetNotificationChannel(ctx context.Context, id string) (GetNotificationChannelRow, error)
	GetPasswordHashByUserID(ctx context.Context, id string) (string, error)
	GetPendingInvitationByCode(ctx context.Context, code string) (GetPendingInvitationByCodeRow, error)
	GetServiceIdentityByID(ctx context.Context, id string) (GetServiceIdentityByIDRow, error)
	// service_identities.sql: scope-limited API keys for production services
	// to fetch their declared secrets at boot. Source:
	// internal/handlers/service_secrets.go
	// ============================================================================
	// Resolve by hashed key (auth middleware lookup)
	// ============================================================================
	GetServiceIdentityByKeyHash(ctx context.Context, keyHash string) (GetServiceIdentityByKeyHashRow, error)
	GetSessionDurationSetting(ctx context.Context) (string, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTOTPSecret(ctx context.Context, id string) (sql.NullString, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserEmailByID(ctx context.Context, id string) (string, error)
	GetUserIDByEmailForInvite(ctx context.Context, email string) (string, error)
	// ============================================================================
	// Unlock (password re-entry) - returns entries with encrypted data for decryption
	// ============================================================================
	GetUserPasswordHash(ctx context.Context, id string) (string, error)
	GetUserTOTPState(ctx context.Context, id string) (GetUserTOTPStateRow, error)
	GetVaultAutoLockMaxMinutes(ctx context.Context) (string, error)
	GetVaultEntryForRotation(ctx context.Context, id string) (GetVaultEntryForRotationRow, error)
	// ============================================================================
	// Vault lookup for service-side resolution (owner-scoped, name-keyed)
	// ============================================================================
	// Scoped to the OWNING user: vault_entries.name is unique only per user, so a
	// name-only lookup would return whichever user's same-named secret SQLite
	// returns first and decrypt it (cross-owner plaintext exfil). A service identity
	// may only resolve secrets owned by its creating user.
	GetVaultEntryForServiceFetch(ctx context.Context, arg GetVaultEntryForServiceFetchParams) (GetVaultEntryForServiceFetchRow, error)
	GetVaultEntryMeta(ctx context.Context, id string) (GetVaultEntryMetaRow, error)
	// ============================================================================
	// Delete entry
	// ============================================================================
	GetVaultEntryName(ctx context.Context, id string) (string, error)
	// ============================================================================
	// Ownership check
	// ============================================================================
	GetVaultEntryOwner(ctx context.Context, id string) (string, error)
	GetVaultEntryTargets(ctx context.Context, id string) (sql.NullString, error)
	// ============================================================================
	// Import - bulk insert (used inside transaction)
	// ============================================================================
	ImportVaultEntry(ctx context.Context, arg ImportVaultEntryParams) error
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	// ============================================================================
	// Audit log
	// ============================================================================
	InsertServiceSecretAudit(ctx context.Context, arg InsertServiceSecretAuditParams) error
	InvalidateUserSessions(ctx context.Context, arg InvalidateUserSessionsParams) error
	ListAPIKeysByUser(ctx context.Context, userID string) ([]ListAPIKeysByUserRow, error)
	ListActivityEntries(ctx context.Context, arg ListActivityEntriesParams) ([]ListActivityEntriesRow, error)
	ListActivityEntriesByAction(ctx context.Context, arg ListActivityEntriesByActionParams) ([]ListActivityEntriesByActionRow, error)
	ListActivityEntriesByUser(ctx context.Context, arg ListActivityEntriesByUserParams) ([]ListActivityEntriesByUserRow, error)
	// ============================================================================
	// List entries (metadata only)
	// ============================================================================
	ListAllVaultEntries(ctx context.Context) ([]ListAllVaultEntriesRow, error)
	ListAuditForServiceIdentity(ctx context.Context, arg ListAuditForServiceIdentityParams) ([]ServiceSecretAudit, error)
	ListEnabledNotificationChannels(ctx context.Context) ([]ListEnabledNotificationChannelsRow, error)
	ListExpiringVaultEntries(ctx context.Context, windowDays string) ([]ListExpiringVaultEntriesRow, error)
	ListInvitations(ctx context.Context) ([]ListInvitationsRow, error)
	ListNotificationChannels(ctx context.Context) ([]ListNotificationChannelsRow, error)
	ListProviderEntries(ctx context.Context) ([]ListProviderEntriesRow, error)
	ListRecentLoginAttemptsByEmail(ctx context.Context, email string) ([]LoginAttempt, error)
	ListRecentServiceSecretAudit(ctx context.Context, limit int64) ([]ServiceSecretAudit, error)
	// ============================================================================
	// Admin CRUD
	// ============================================================================
	ListServiceIdentities(ctx context.Context) ([]ListServiceIdentitiesRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersWithEntryCount(ctx context.Context) ([]ListUsersWithEntryCountRow, error)
	ListUsersWithTOTPSecret(ctx context.Context) ([]ListUsersWithTOTPSecretRow, error)
	ListVaultEntriesByUser(ctx context.Context, userID string) ([]ListVaultEntriesByUserRow, error)
	ListVaultEntriesForMetaBackfill(ctx context.Context) ([]ListVaultEntriesForMetaBackfillRow, error)
	ListVaultEntriesNeedingRotation(ctx context.Context) ([]ListVaultEntriesNeedingRotationRow, error)
	ListVaultEntriesV1(ctx context.Context) ([]ListVaultEntriesV1Row, error)
	ListVaultEntriesWithSecrets(ctx context.Context, userID string) ([]ListVaultEntriesWithSecretsRow, error)
	// ============================================================================
	// Import - conflict detection
	// ============================================================================
	ListVaultEntryNamesByUser(ctx context.Context, userID string) ([]string, error)
	MarkInvitationRedeemed(ctx context.Context, arg MarkInvitationRedeemedParams) error
	// ============================================================================
	// URL matching (browser extension autofill)
	// ============================================================================
	MatchVaultEntriesByURL(ctx context.Context, arg MatchVaultEntriesByURLParams) ([]MatchVaultEntriesByURLRow, error)
	MigrateVaultEntryEncryption(ctx context.Context, arg MigrateVaultEntryEncryptionParams) error
	// ============================================================================
	// Resolve {{vault:NAME}} references (scoped to requesting user's vault)
	// ============================================================================
	ResolveVaultReference(ctx context.Context, arg ResolveVaultReferenceParams) (ResolveVaultReferenceRow, error)
	RevokeServiceIdentity(ctx context.Context, id string) (sql.Result, error)
	// ============================================================================
	// Rotate (generate new secret value)
	// ============================================================================
	RotateVaultEntryValue(ctx context.Context, arg RotateVaultEntryValueParams) (sql.Result, error)
	// Seeds the capability-bridge columns from the provider defaults at
	// enrollment time. Only fills untouched rows so explicit per-entry
	// patterns are never overwritten.
	SeedVaultEntryCapabilityDefaults(ctx context.Context, arg SeedVaultEntryCapabilityDefaultsParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (sql.Result, error)
	StoreTOTPSecret(ctx context.Context, arg StoreTOTPSecretParams) error
	TouchServiceIdentityLastUsed(ctx context.Context, id string) error
	UpdateNotificationChannelEnabled(ctx context.Context, arg UpdateNotificationChannelEnabledParams) (sql.Result, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateRecoveryCodes(ctx context.Context, arg UpdateRecoveryCodesParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error)
	UpdateVaultEntryAliasURL(ctx context.Context, arg UpdateVaultEntryAliasURLParams) error
	UpdateVaultEntryAutoLogin(ctx context.Context, arg UpdateVaultEntryAutoLoginParams) error
	UpdateVaultEntryCategory(ctx context.Context, arg UpdateVaultEntryCategoryParams) error
	UpdateVaultEntryExpiresAt(ctx context.Context, arg UpdateVaultEntryExpiresAtParams) error
	// ============================================================================
	// Update entry - individual metadata fields
	// ============================================================================
	UpdateVaultEntryName(ctx context.Context, arg UpdateVaultEntryNameParams) error
	UpdateVaultEntryNotes(ctx context.Context, arg UpdateVaultEntryNotesParams) error
	// ============================================================================
	// Provider integration (API key rotation)
	// ============================================================================
	UpdateVaultEntryProvider(ctx context.Context, arg UpdateVaultEntryProviderParams) error
	UpdateVaultEntryProviderMeta(ctx context.Context, arg UpdateVaultEntryProviderMetaParams) error
	UpdateVaultEntryRotationError(ctx context.Context, arg UpdateVaultEntryRotationErrorParams) error
	UpdateVaultEntryRotationInterval(ctx context.Context, arg UpdateVaultEntryRotationIntervalParams) error
	UpdateVaultEntryRotationLog(ctx context.Context, arg UpdateVaultEntryRotationLogParams) error
	UpdateVaultEntryRotationTargets(ctx context.Context, arg UpdateVaultEntryRotationTargetsParams) error
	UpdateVaultEntryURL(ctx context.Context, arg UpdateVaultEntryURLParams) error
	UpdateVaultEntryUsername(ctx context.Context, arg UpdateVaultEntryUsernameParams) error
	// ============================================================================
	// Update entry - encrypted value (re-encrypt + rotate timestamp)
	// ============================================================================
	UpdateVaultEntryValue(ctx context.Context, arg UpdateVaultEntryValueParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
