// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_identities.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createServiceIdentity = `-- name: CreateServiceIdentity :exec
INSERT INTO service_identities
  (id, name, description, allowed_secrets, key_hash, key_prefix,
   expires_at, created_by_user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateServiceIdentityParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	AllowedSecrets  string         `json:"allowed_secrets"`
	KeyHash         string         `json:"key_hash"`
	KeyPrefix       string         `json:"key_prefix"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

func (q *Queries) CreateServiceIdentity(ctx context.Context, arg CreateServiceIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createServiceIdentity,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AllowedSecrets,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	return err
}

const deleteServiceIdentity = `-- name: DeleteServiceIdentity :execresult
DELETE FROM service_identities WHERE id = ?
`

func (q *Queries) DeleteServiceIdentity(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteServiceIdentity, id)
}

const getServiceIdentityByID = `-- name: GetServiceIdentityByID :one
SELECT id, name, description, allowed_secrets, key_prefix,
       last_used_at, expires_at, revoked_at, created_at
FROM service_identities
WHERE id = ?
`

type GetServiceIdentityByIDRow struct {
	ID             string       `json:"id"`
	Name           string       `json:"name"`
	Description    string       `json:"description"`
	AllowedSecrets string       `json:"allowed_secrets"`
	KeyPrefix      string       `json:"key_prefix"`
	LastUsedAt     sql.NullTime `json:"last_used_at"`
	ExpiresAt      sql.NullTime `json:"expires_at"`
	RevokedAt      sql.NullTime `json:"revoked_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

func (q *Queries) GetServiceIdentityByID(ctx context.Context, id string) (GetServiceIdentityByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceIdentityByID, id)
	var i GetServiceIdentityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedSecrets,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceIdentityByKeyHash = `-- name: GetServiceIdentityByKeyHash :one


SELECT id, name, description, allowed_secrets, key_prefix,
       last_used_at, expires_at, revoked_at, created_at, created_by_user_id
FROM service_identities
WHERE key_hash = ?
`

type GetServiceIdentityByKeyHashRow struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	AllowedSecrets  string         `json:"allowed_secrets"`
	KeyPrefix       string         `json:"key_prefix"`
	LastUsedAt      sql.NullTime   `json:"last_used_at"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	RevokedAt       sql.NullTime   `json:"revoked_at"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
}

// service_identities.sql: scope-limited API keys for production services
// to fetch their declared secrets at boot. Source:
// internal/handlers/service_secrets.go
// ============================================================================
// Resolve by hashed key (auth middleware lookup)
// ============================================================================
func (q *Queries) GetServiceIdentityByKeyHash(ctx context.Context, keyHash string) (GetServiceIdentityByKeyHashRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceIdentityByKeyHash, keyHash)
	var i GetServiceIdentityByKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowedSecrets,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const insertServiceSecretAudit = `-- name: InsertServiceSecretAudit :exec

INSERT INTO service_secret_audit
  (id, service_identity_id, service_name, event, secret_names, error, remote_ip)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertServiceSecretAuditParams struct {
	ID                string         `json:"id"`
	ServiceIdentityID sql.NullString `json:"service_identity_id"`
	ServiceName       string         `json:"service_name"`
	Event             string         `json:"event"`
	SecretNames       string         `json:"secret_names"`
	Error             string         `json:"error"`
	RemoteIp          string         `json:"remote_ip"`
}

// ============================================================================
// Audit log
// ============================================================================
func (q *Queries) InsertServiceSecretAudit(ctx context.Context, arg InsertServiceSecretAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceSecretAudit,
		arg.ID,
		arg.ServiceIdentityID,
		arg.ServiceName,
		arg.Event,
		arg.SecretNames,
		arg.Error,
		arg.RemoteIp,
	)
	return err
}

const listAuditForServiceIdentity = `-- name: ListAuditForServiceIdentity :many
SELECT id, service_identity_id, service_name, event, secret_names,
       error, remote_ip, occurred_at
FROM service_secret_audit
WHERE service_identity_id = ?
ORDER BY occurred_at DESC
LIMIT ?
`

type ListAuditForServiceIdentityParams struct {
	ServiceIdentityID sql.NullString `json:"service_identity_id"`
	Limit             int64          `json:"limit"`
}

func (q *Queries) ListAuditForServiceIdentity(ctx context.Context, arg ListAuditForServiceIdentityParams) ([]ServiceSecretAudit, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForServiceIdentity, arg.ServiceIdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSecretAudit{}
	for rows.Next() {
		var i ServiceSecretAudit
		if err := rows.Scan(
			&i.ID,
			&i.ServiceIdentityID,
			&i.ServiceName,
			&i.Event,
			&i.SecretNames,
			&i.Error,
			&i.RemoteIp,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalVaultEntriesForServiceFetch = `-- name: ListPersonalVaultEntriesForServiceFetch :many

SELECT id, name, encrypted_value, nonce, encryption_version
FROM vault_entries
WHERE user_id = ? AND collection_id IS NULL
`

type ListPersonalVaultEntriesForServiceFetchRow struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	EncryptedValue    []byte        `json:"encrypted_value"`
	Nonce             []byte        `json:"nonce"`
	EncryptionVersion sql.NullInt64 `json:"encryption_version"`
}

// ============================================================================
// Vault lookup for service-side resolution (owner-scoped)
// ============================================================================
// Scoped to the OWNING user: vault_entries.name is unique only per user, so a
// name-only lookup would return whichever user's same-named secret SQLite
// returns first and decrypt it (cross-owner plaintext exfil). A service identity
// may only resolve secrets owned by its creating user.
//
// Also restricted to PERSONAL entries (collection_id IS NULL). A service
// identity's allowed_secrets is a NAME whitelist, and any editor of a shared
// collection can rewrite the value of an entry that lives in that collection
// even when the creating user still owns the row. Without this predicate an
// editor could therefore control what a machine identity fetches (or swap it for
// a value of their choosing) purely by editing a shared entry. Machine
// identities resolve only secrets their creator holds privately.
//
// THE NAME PREDICATE IS GONE FROM THE SQL, and it had to be. Since 00040 this
// column holds randomized AES-GCM ciphertext, so `WHERE name = ?` against the
// whitelist's cleartext matched NOTHING: every service-identity secret fetch
// missed, and the handler answered 200 with an empty secrets map, so containers
// booted credential-less believing they had succeeded.
//
// It is deliberately NOT replaced with `WHERE name_bidx = ?`. The boot sweep in
// vault.go leaves a row whose sealed name would collide on UNIQUE(user_id,
// name_bidx) cleartext with an EMPTY name_bidx, forever, on purpose. A bidx
// lookup silently strands exactly those rows, which is a worse failure than the
// one being fixed because it is invisible. The name is matched in Go instead,
// on the decrypted value, which resolves swept and unswept rows alike.
//
// BOTH AUTHORIZATION PREDICATES STAY IN SQL. user_id is what stops a service
// identity reaching another owner's secret and collection_id IS NULL is what
// stops a collection editor choosing what a machine identity fetches. Neither
// may move into the Go filter: a name match that runs after a widened query is
// not an authorization check.
func (q *Queries) ListPersonalVaultEntriesForServiceFetch(ctx context.Context, userID string) ([]ListPersonalVaultEntriesForServiceFetchRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalVaultEntriesForServiceFetch, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalVaultEntriesForServiceFetchRow{}
	for rows.Next() {
		var i ListPersonalVaultEntriesForServiceFetchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EncryptedValue,
			&i.Nonce,
			&i.EncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentServiceSecretAudit = `-- name: ListRecentServiceSecretAudit :many
SELECT id, service_identity_id, service_name, event, secret_names,
       error, remote_ip, occurred_at
FROM service_secret_audit
ORDER BY occurred_at DESC
LIMIT ?
`

func (q *Queries) ListRecentServiceSecretAudit(ctx context.Context, limit int64) ([]ServiceSecretAudit, error) {
	rows, err := q.db.QueryContext(ctx, listRecentServiceSecretAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSecretAudit{}
	for rows.Next() {
		var i ServiceSecretAudit
		if err := rows.Scan(
			&i.ID,
			&i.ServiceIdentityID,
			&i.ServiceName,
			&i.Event,
			&i.SecretNames,
			&i.Error,
			&i.RemoteIp,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceIdentities = `-- name: ListServiceIdentities :many

SELECT si.id, si.name, si.description, si.allowed_secrets, si.key_prefix,
       si.last_used_at, si.expires_at, si.revoked_at, si.created_at,
       u.email AS owner_email,
       COALESCE(u.totp_enabled, 0) = 1 AS owner_totp_enabled
FROM service_identities si
LEFT JOIN users u ON u.id = si.created_by_user_id
ORDER BY si.created_at DESC
`

type ListServiceIdentitiesRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	AllowedSecrets   string         `json:"allowed_secrets"`
	KeyPrefix        string         `json:"key_prefix"`
	LastUsedAt       sql.NullTime   `json:"last_used_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
	OwnerEmail       sql.NullString `json:"owner_email"`
	OwnerTotpEnabled bool           `json:"owner_totp_enabled"`
}

// ============================================================================
// Admin CRUD
// ============================================================================
// Owner email + enrolment status ride along so an admin can see, from this
// ONE existing list, every identity FetchOwnSecrets will start refusing the
// moment require_totp is turned on -- before a boot failure is how anyone
// finds out. LEFT JOIN because created_by_user_id is nullable and a deleted
// owner must still show up in the list (as unenrolled, which is correct: a
// deleted owner's identity is already refused by the owner-liveness check).
func (q *Queries) ListServiceIdentities(ctx context.Context) ([]ListServiceIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceIdentitiesRow{}
	for rows.Next() {
		var i ListServiceIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AllowedSecrets,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.OwnerTotpEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceIdentitiesByUser = `-- name: ListServiceIdentitiesByUser :many
SELECT id, name FROM service_identities
WHERE created_by_user_id = ? AND revoked_at IS NULL
`

type ListServiceIdentitiesByUserRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListServiceIdentitiesByUser(ctx context.Context, createdByUserID sql.NullString) ([]ListServiceIdentitiesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceIdentitiesByUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceIdentitiesByUserRow{}
	for rows.Next() {
		var i ListServiceIdentitiesByUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeServiceIdentitiesByUser = `-- name: RevokeServiceIdentitiesByUser :execresult
UPDATE service_identities
SET revoked_at = CURRENT_TIMESTAMP
WHERE created_by_user_id = ? AND revoked_at IS NULL
`

// Offboarding: revoke every still-live service key a departing user minted.
// FetchOwnSecrets resolves secrets as the identity's created_by_user_id, so an
// un-revoked key outlives its owner and keeps reading their personal vault.
// The runtime gate in FetchOwnSecrets refuses those anyway; revoking here is
// what makes the revocation VISIBLE in the identities list instead of the key
// silently 401ing at the next boot.
func (q *Queries) RevokeServiceIdentitiesByUser(ctx context.Context, createdByUserID sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeServiceIdentitiesByUser, createdByUserID)
}

const revokeServiceIdentity = `-- name: RevokeServiceIdentity :execresult
UPDATE service_identities
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeServiceIdentity(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeServiceIdentity, id)
}

const touchServiceIdentityLastUsed = `-- name: TouchServiceIdentityLastUsed :exec
UPDATE service_identities
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchServiceIdentityLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchServiceIdentityLastUsed, id)
	return err
}
