// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const countRecentFailedLoginAttemptsByEmail = `-- name: CountRecentFailedLoginAttemptsByEmail :one
SELECT COUNT(*) FROM login_attempts
WHERE email = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

func (q *Queries) CountRecentFailedLoginAttemptsByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLoginAttemptsByIP = `-- name: CountRecentFailedLoginAttemptsByIP :one
SELECT COUNT(*) FROM login_attempts
WHERE ip_address = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

func (q *Queries) CountRecentFailedLoginAttemptsByIP(ctx context.Context, ipAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO login_attempts (email, ip_address, success)
VALUES (?, ?, ?)
`

type CreateLoginAttemptParams struct {
	Email     string `json:"email"`
	IpAddress string `json:"ip_address"`
	Success   int64  `json:"success"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createLoginAttempt, arg.Email, arg.IpAddress, arg.Success)
	return err
}

const listRecentLoginAttemptsByEmail = `-- name: ListRecentLoginAttemptsByEmail :many
SELECT id, email, ip_address, success, created_at
FROM login_attempts
WHERE email = ?
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListRecentLoginAttemptsByEmail(ctx context.Context, email string) ([]LoginAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLoginAttemptsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IpAddress,
			&i.Success,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
