// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const countRecentFailedLoginAttemptsByEmailAndScope = `-- name: CountRecentFailedLoginAttemptsByEmailAndScope :one
SELECT COUNT(*) FROM login_attempts
WHERE email = ? AND scope = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

type CountRecentFailedLoginAttemptsByEmailAndScopeParams struct {
	Email string `json:"email"`
	Scope string `json:"scope"`
}

// Failures at ONE door, for one address.
//
// Scope is not optional and there is deliberately no unscoped variant: an
// unscoped count is what let five wrong passwords at the public login endpoint
// refuse the owner's own authenticated enrolment call, which under require_totp
// holds the whole vault shut. See migration 00042. Adding a query that counts
// across scopes reopens it.
func (q *Queries) CountRecentFailedLoginAttemptsByEmailAndScope(ctx context.Context, arg CountRecentFailedLoginAttemptsByEmailAndScopeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByEmailAndScope, arg.Email, arg.Scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLoginAttemptsByIP = `-- name: CountRecentFailedLoginAttemptsByIP :one
SELECT COUNT(*) FROM login_attempts
WHERE ip_address = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

// Deliberately scope-BLIND, unlike the per-email counter above: this is the
// credential-stuffing brake, keyed on the attacker's own address, so an
// outsider can only ever fill it against themselves. Splitting it would weaken
// a control without closing anything.
func (q *Queries) CountRecentFailedLoginAttemptsByIP(ctx context.Context, ipAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO login_attempts (email, ip_address, success, scope)
VALUES (?, ?, ?, ?)
`

type CreateLoginAttemptParams struct {
	Email     string `json:"email"`
	IpAddress string `json:"ip_address"`
	Success   int64  `json:"success"`
	Scope     string `json:"scope"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createLoginAttempt,
		arg.Email,
		arg.IpAddress,
		arg.Success,
		arg.Scope,
	)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

// Server-side session records. A JWT carries the session id as its jti claim;
// the auth middleware rejects any token whose session row is missing, revoked,
// or idle past the configured window. This turns stateless JWTs into revocable
// sessions so logout and inactivity kill a leaked token immediately.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const listRecentLoginAttemptsByEmail = `-- name: ListRecentLoginAttemptsByEmail :many
SELECT id, email, ip_address, success, created_at
FROM login_attempts
WHERE email = ?
ORDER BY created_at DESC
LIMIT 20
`

type ListRecentLoginAttemptsByEmailRow struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	IpAddress string       `json:"ip_address"`
	Success   int64        `json:"success"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListRecentLoginAttemptsByEmail(ctx context.Context, email string) ([]ListRecentLoginAttemptsByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLoginAttemptsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentLoginAttemptsByEmailRow{}
	for rows.Next() {
		var i ListRecentLoginAttemptsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IpAddress,
			&i.Success,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneLoginAttempts = `-- name: PruneLoginAttempts :execresult
DELETE FROM login_attempts WHERE created_at < datetime('now', ?)
`

// Retention sweep for login_attempts.
//
// Nothing purged this table, so it accumulated a plaintext email and source IP
// per attempt for the life of the deployment. It is the one table an
// UNAUTHENTICATED caller can put a row of their choosing into, and since the
// 2026-08-05 enumeration fix an address with no account writes a row too, so it
// grows faster than it used to.
//
// Deleting old rows costs nothing, because this table is a rate-limiting
// mechanism and not an audit trail. Every live reader (the per-email and per-IP
// lockout counts, and vault.reauthLocked which reuses the per-email one) looks
// back exactly 15 minutes; ListRecentLoginAttemptsByEmail has no callers at all.
// The actual audit trail for logins is activity_log, which is append-only and
// tamper-evident and is not touched by this.
//
// The window is passed in rather than baked here so one Go constant is the
// single source of truth, and TestLoginAttemptRetentionOutlivesEveryReader can
// derive the readers' windows from this file and prove the constant exceeds all
// of them.
func (q *Queries) PruneLoginAttempts(ctx context.Context, datetime interface{}) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneLoginAttempts, datetime)
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, userID)
	return err
}
