// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const countRecentFailedLoginAttemptsByEmail = `-- name: CountRecentFailedLoginAttemptsByEmail :one
SELECT COUNT(*) FROM login_attempts
WHERE email = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

func (q *Queries) CountRecentFailedLoginAttemptsByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLoginAttemptsByIP = `-- name: CountRecentFailedLoginAttemptsByIP :one
SELECT COUNT(*) FROM login_attempts
WHERE ip_address = ? AND success = 0
  AND created_at > datetime('now', '-15 minutes')
`

func (q *Queries) CountRecentFailedLoginAttemptsByIP(ctx context.Context, ipAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedLoginAttemptsByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO login_attempts (email, ip_address, success)
VALUES (?, ?, ?)
`

type CreateLoginAttemptParams struct {
	Email     string `json:"email"`
	IpAddress string `json:"ip_address"`
	Success   int64  `json:"success"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createLoginAttempt, arg.Email, arg.IpAddress, arg.Success)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

// Server-side session records. A JWT carries the session id as its jti claim;
// the auth middleware rejects any token whose session row is missing, revoked,
// or idle past the configured window. This turns stateless JWTs into revocable
// sessions so logout and inactivity kill a leaked token immediately.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const listRecentLoginAttemptsByEmail = `-- name: ListRecentLoginAttemptsByEmail :many
SELECT id, email, ip_address, success, created_at
FROM login_attempts
WHERE email = ?
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListRecentLoginAttemptsByEmail(ctx context.Context, email string) ([]LoginAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLoginAttemptsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IpAddress,
			&i.Success,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, userID)
	return err
}
