// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const cASRecoveryCodes = `-- name: CASRecoveryCodes :execresult
UPDATE users SET totp_recovery_codes = ?
WHERE id = ? AND COALESCE(totp_recovery_codes, '') = ?
`

type CASRecoveryCodesParams struct {
	TotpRecoveryCodes   sql.NullString `json:"totp_recovery_codes"`
	ID                  string         `json:"id"`
	TotpRecoveryCodes_2 sql.NullString `json:"totp_recovery_codes_2"`
}

// Compare-and-swap on the recovery-code list.
//
// Consumption was a read-modify-write: read the JSON array, drop the used code, write
// the whole column back. With a plain UPDATE that is a lost update, and each code is a
// standalone 64-bit 2FA bypass, so a code the user has already redeemed and crossed off
// their printed list stays a working second factor.
//
// Two ways in: two concurrent logins each carrying a code both read before either
// writes, and a failed persist that still completed the login. Comparing the column
// itself means the second writer loses and retries against the winner's list.
func (q *Queries) CASRecoveryCodes(ctx context.Context, arg CASRecoveryCodesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cASRecoveryCodes, arg.TotpRecoveryCodes, arg.ID, arg.TotpRecoveryCodes_2)
}

const claimTOTPStep = `-- name: ClaimTOTPStep :execresult
UPDATE users SET totp_last_step = ?
WHERE id = ? AND (totp_last_step IS NULL OR totp_last_step < ?)
`

type ClaimTOTPStepParams struct {
	TotpLastStep   sql.NullInt64 `json:"totp_last_step"`
	ID             string        `json:"id"`
	TotpLastStep_2 sql.NullInt64 `json:"totp_last_step_2"`
}

// Spend a TOTP time step, monotonically.
//
// Affects zero rows when the step has already been used (or an older one is being
// replayed), which is how a captured code stops being reusable inside its own window.
func (q *Queries) ClaimTOTPStep(ctx context.Context, arg ClaimTOTPStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimTOTPStep, arg.TotpLastStep, arg.ID, arg.TotpLastStep_2)
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin' AND disabled = 0
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFirstAdmin = `-- name: CreateFirstAdmin :one
INSERT INTO users (email, password_hash, name, role)
SELECT ?, ?, ?, 'admin'
WHERE NOT EXISTS (SELECT 1 FROM users)
RETURNING id, email, name, role, created_at
`

type CreateFirstAdminParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
}

type CreateFirstAdminRow struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// The first-run admin, created ONLY while the users table is empty.
//
// Register used to read CountUsers, then decode the request body, then INSERT, with
// no transaction and no recheck. The gap between the check and the write is not
// instantaneous and it is ATTACKER-EXTENDABLE: the body decode sits inside it and the
// server's ReadTimeout is 30s, so a client that trickles its body holds the window
// open for as long as it likes.
//
// Proven, not theorised: a request that passed the count==0 gate and then stalled
// mid-body still created an account after a legitimate operator completed setup,
// giving 2 users / 2 admins. Register is UNAUTHENTICATED and mints an ADMIN, so that
// is a full takeover of a fresh instance by anyone who can reach it during setup.
//
// The check and the insert are now one statement, so there is no window at all.
// A caller that affects zero rows must treat that as "setup already completed".
func (q *Queries) CreateFirstAdmin(ctx context.Context, arg CreateFirstAdminParams) (CreateFirstAdminRow, error) {
	row := q.db.QueryRowContext(ctx, createFirstAdmin, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateFirstAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES (?, ?, ?, ?)
RETURNING id, email, name, role, created_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Role         string         `json:"role"`
}

type CreateUserRow struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const deleteUserIfNotLastAdmin = `-- name: DeleteUserIfNotLastAdmin :execresult
DELETE FROM users
WHERE users.id = ?
  AND (
    users.role != 'admin'
    OR users.disabled = 1
    OR (SELECT COUNT(*) FROM users AS a WHERE a.role = 'admin' AND a.disabled = 0) > 1
  )
`

// Hard delete that refuses to remove the last active admin.
func (q *Queries) DeleteUserIfNotLastAdmin(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserIfNotLastAdmin, id)
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_enabled = 0, totp_secret = '', totp_recovery_codes = '' WHERE id = ?
`

func (q *Queries) DisableTOTP(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_enabled = 1, totp_recovery_codes = ? WHERE id = ?
`

type EnableTOTPParams struct {
	TotpRecoveryCodes sql.NullString `json:"totp_recovery_codes"`
	ID                string         `json:"id"`
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.ExecContext(ctx, enableTOTP, arg.TotpRecoveryCodes, arg.ID)
	return err
}

const getPasswordHashByUserID = `-- name: GetPasswordHashByUserID :one
SELECT password_hash FROM users WHERE id = ?
`

func (q *Queries) GetPasswordHashByUserID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHashByUserID, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getTOTPSecret = `-- name: GetTOTPSecret :one
SELECT totp_secret FROM users WHERE id = ?
`

func (q *Queries) GetTOTPSecret(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTOTPSecret, id)
	var totp_secret sql.NullString
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, disabled, created_at
FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Role         string         `json:"role"`
	Disabled     int64          `json:"disabled"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, disabled, totp_enabled, created_at
FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Role        string         `json:"role"`
	Disabled    int64          `json:"disabled"`
	TotpEnabled sql.NullInt64  `json:"totp_enabled"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Disabled,
		&i.TotpEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEmailByID = `-- name: GetUserEmailByID :one
SELECT email FROM users WHERE id = ?
`

func (q *Queries) GetUserEmailByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getUserTOTPState = `-- name: GetUserTOTPState :one
SELECT totp_enabled, totp_secret, totp_recovery_codes
FROM users WHERE id = ?
`

type GetUserTOTPStateRow struct {
	TotpEnabled       sql.NullInt64  `json:"totp_enabled"`
	TotpSecret        sql.NullString `json:"totp_secret"`
	TotpRecoveryCodes sql.NullString `json:"totp_recovery_codes"`
}

func (q *Queries) GetUserTOTPState(ctx context.Context, id string) (GetUserTOTPStateRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTOTPState, id)
	var i GetUserTOTPStateRow
	err := row.Scan(&i.TotpEnabled, &i.TotpSecret, &i.TotpRecoveryCodes)
	return i, err
}

const invalidateUserSessions = `-- name: InvalidateUserSessions :exec
UPDATE users SET sessions_valid_after = ? WHERE id = ?
`

type InvalidateUserSessionsParams struct {
	SessionsValidAfter int64  `json:"sessions_valid_after"`
	ID                 string `json:"id"`
}

func (q *Queries) InvalidateUserSessions(ctx context.Context, arg InvalidateUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, invalidateUserSessions, arg.SessionsValidAfter, arg.ID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, disabled, totp_enabled, created_at
FROM users ORDER BY created_at ASC
`

type ListUsersRow struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Role        string         `json:"role"`
	Disabled    int64          `json:"disabled"`
	TotpEnabled sql.NullInt64  `json:"totp_enabled"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Disabled,
			&i.TotpEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithTOTPSecret = `-- name: ListUsersWithTOTPSecret :many
SELECT id, totp_secret FROM users WHERE totp_secret != ''
`

type ListUsersWithTOTPSecretRow struct {
	ID         string         `json:"id"`
	TotpSecret sql.NullString `json:"totp_secret"`
}

func (q *Queries) ListUsersWithTOTPSecret(ctx context.Context) ([]ListUsersWithTOTPSecretRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithTOTPSecret)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithTOTPSecretRow{}
	for rows.Next() {
		var i ListUsersWithTOTPSecretRow
		if err := rows.Scan(&i.ID, &i.TotpSecret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :execresult
UPDATE users SET disabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetUserDisabledParams struct {
	Disabled int64  `json:"disabled"`
	ID       string `json:"id"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUserDisabled, arg.Disabled, arg.ID)
}

const setUserDisabledIfNotLastAdmin = `-- name: SetUserDisabledIfNotLastAdmin :execresult
UPDATE users SET disabled = ?
WHERE users.id = ?
  AND (
    ? = 0
    OR users.role != 'admin'
    OR users.disabled = 1
    OR (SELECT COUNT(*) FROM users AS a WHERE a.role = 'admin' AND a.disabled = 0) > 1
  )
`

type SetUserDisabledIfNotLastAdminParams struct {
	Disabled int64       `json:"disabled"`
	ID       string      `json:"id"`
	Column3  interface{} `json:"column_3"`
}

// Disable that refuses to disable the last active admin. Same reasoning as
// UpdateUserRoleIfNotLastAdmin.
func (q *Queries) SetUserDisabledIfNotLastAdmin(ctx context.Context, arg SetUserDisabledIfNotLastAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUserDisabledIfNotLastAdmin, arg.Disabled, arg.ID, arg.Column3)
}

const storeTOTPSecret = `-- name: StoreTOTPSecret :exec
UPDATE users SET totp_secret = ? WHERE id = ?
`

type StoreTOTPSecretParams struct {
	TotpSecret sql.NullString `json:"totp_secret"`
	ID         string         `json:"id"`
}

func (q *Queries) StoreTOTPSecret(ctx context.Context, arg StoreTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, storeTOTPSecret, arg.TotpSecret, arg.ID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateRecoveryCodes = `-- name: UpdateRecoveryCodes :exec
UPDATE users SET totp_recovery_codes = ? WHERE id = ?
`

type UpdateRecoveryCodesParams struct {
	TotpRecoveryCodes sql.NullString `json:"totp_recovery_codes"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateRecoveryCodes(ctx context.Context, arg UpdateRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, updateRecoveryCodes, arg.TotpRecoveryCodes, arg.ID)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserNameParams struct {
	Name sql.NullString `json:"name"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserName, arg.Name, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :execresult
UPDATE users SET role = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
}

const updateUserRoleIfNotLastAdmin = `-- name: UpdateUserRoleIfNotLastAdmin :execresult
UPDATE users SET role = ?
WHERE users.id = ?
  AND (
    ? = 'admin'
    OR users.role != 'admin'
    OR users.disabled = 1
    OR (SELECT COUNT(*) FROM users AS a WHERE a.role = 'admin' AND a.disabled = 0) > 1
  )
`

type UpdateUserRoleIfNotLastAdminParams struct {
	Role    string      `json:"role"`
	ID      string      `json:"id"`
	Column3 interface{} `json:"column_3"`
}

// Role change that REFUSES to remove the last active admin, atomically.
//
// ensureNotLastAdmin was a check-then-act: COUNT(*) in one statement, the write
// in another, with no transaction and no CAS between them. Two admins demoting
// each other concurrently (or one admin demoted twice by two tabs) both saw
// count = 2, both proceeded, and the instance was left with zero admins. Nothing
// in the product can create one back: CreateFirstAdmin is gated on the users
// table being empty, and every admin route needs an admin. The recovery is
// hand-editing the database.
//
// The guard travels WITH the write here, so the count and the update see the
// same snapshot. RowsAffected = 0 means it was refused.
func (q *Queries) UpdateUserRoleIfNotLastAdmin(ctx context.Context, arg UpdateUserRoleIfNotLastAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRoleIfNotLastAdmin, arg.Role, arg.ID, arg.Column3)
}
