// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault.sql

package db

import (
	"context"
	"database/sql"
)

const countVaultEntriesV1 = `-- name: CountVaultEntriesV1 :one


SELECT COUNT(*) FROM vault_entries WHERE encryption_version = 1
`

// vault.sql: Secrets vault queries - CRUD, encryption migration, unlock,
// per-field updates, rotation, URL matching, reference resolution, import.
// Source: internal/handlers/vault.go, internal/handlers/vault_import.go
// Copied verbatim from dockyard so generated method names stay identical.
// ============================================================================
// Encryption migration (v1 SHA-256 -> v2 PBKDF2)
// ============================================================================
func (q *Queries) CountVaultEntriesV1(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVaultEntriesV1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVaultEntry = `-- name: CreateVaultEntry :exec

INSERT INTO vault_entries (id, user_id, name, encrypted_value, nonce, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, provider, provider_meta, auto_rotate, url_bidx, alias_url_bidx, encryption_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 2)
`

type CreateVaultEntryParams struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	UrlBidx              string         `json:"url_bidx"`
	AliasUrlBidx         string         `json:"alias_url_bidx"`
}

// ============================================================================
// Create entry
// ============================================================================
func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, createVaultEntry,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedValue,
		arg.Nonce,
		arg.Url,
		arg.AliasUrl,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.AutoLogin,
		arg.RotationIntervalDays,
		arg.ExpiresAt,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.UrlBidx,
		arg.AliasUrlBidx,
	)
	return err
}

const deleteVaultEntry = `-- name: DeleteVaultEntry :execresult
DELETE FROM vault_entries WHERE id = ?
`

func (q *Queries) DeleteVaultEntry(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVaultEntry, id)
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one

SELECT password_hash FROM users WHERE id = ?
`

// ============================================================================
// Unlock (password re-entry) - returns entries with encrypted data for decryption
// ============================================================================
func (q *Queries) GetUserPasswordHash(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getVaultEntryForRotation = `-- name: GetVaultEntryForRotation :one
SELECT id, user_id, name, encrypted_value, nonce, encryption_version, provider, provider_meta, rotation_interval_days, last_rotated_at, rotation_log, rotation_targets
FROM vault_entries WHERE id = ?
`

type GetVaultEntryForRotationRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	EncryptionVersion    sql.NullInt64  `json:"encryption_version"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	RotationLog          sql.NullString `json:"rotation_log"`
	RotationTargets      sql.NullString `json:"rotation_targets"`
}

// On-demand path: fetch a single entry (with its secret + rotation fields) by
// id, with NO auto_rotate filter. This backs the manual Rotate and ValidateKey
// handlers plus the rotation-log re-fetches, all of which are user-triggered
// operations that MUST work for every entry regardless of auto_rotate (this is
// an on-demand rotation product). The scheduled sweep uses a separate query,
// ListVaultEntriesNeedingRotation, which keeps its own auto_rotate = 1 gate.
// Do NOT re-add "AND auto_rotate = 1" here: it makes manual rotate panic
// (empty row -> nil nonce -> GCM) and validate 404 for every entry that is not
// auto-rotating.
func (q *Queries) GetVaultEntryForRotation(ctx context.Context, id string) (GetVaultEntryForRotationRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryForRotation, id)
	var i GetVaultEntryForRotationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EncryptedValue,
		&i.Nonce,
		&i.EncryptionVersion,
		&i.Provider,
		&i.ProviderMeta,
		&i.RotationIntervalDays,
		&i.LastRotatedAt,
		&i.RotationLog,
		&i.RotationTargets,
	)
	return i, err
}

const getVaultEntryMeta = `-- name: GetVaultEntryMeta :one
SELECT id, name, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, last_rotated_at, provider, provider_meta, auto_rotate, last_rotation_error, created_at, updated_at
FROM vault_entries WHERE id = ?
`

type GetVaultEntryMetaRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetVaultEntryMeta(ctx context.Context, id string) (GetVaultEntryMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryMeta, id)
	var i GetVaultEntryMetaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.AliasUrl,
		&i.Username,
		&i.Category,
		&i.Notes,
		&i.AutoLogin,
		&i.RotationIntervalDays,
		&i.ExpiresAt,
		&i.LastRotatedAt,
		&i.Provider,
		&i.ProviderMeta,
		&i.AutoRotate,
		&i.LastRotationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVaultEntryName = `-- name: GetVaultEntryName :one

SELECT name FROM vault_entries WHERE id = ?
`

// ============================================================================
// Delete entry
// ============================================================================
func (q *Queries) GetVaultEntryName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getVaultEntryOwner = `-- name: GetVaultEntryOwner :one

SELECT user_id FROM vault_entries WHERE id = ?
`

// ============================================================================
// Ownership check
// ============================================================================
func (q *Queries) GetVaultEntryOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryOwner, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getVaultEntryTargets = `-- name: GetVaultEntryTargets :one
SELECT rotation_targets FROM vault_entries WHERE id = ?
`

func (q *Queries) GetVaultEntryTargets(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getVaultEntryTargets, id)
	var rotation_targets sql.NullString
	err := row.Scan(&rotation_targets)
	return rotation_targets, err
}

const importVaultEntry = `-- name: ImportVaultEntry :exec

INSERT INTO vault_entries (id, user_id, name, encrypted_value, nonce, url, username, category, notes, url_bidx, encryption_version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 2, datetime('now'), datetime('now'))
`

type ImportVaultEntryParams struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Name           string         `json:"name"`
	EncryptedValue []byte         `json:"encrypted_value"`
	Nonce          []byte         `json:"nonce"`
	Url            sql.NullString `json:"url"`
	Username       sql.NullString `json:"username"`
	Category       sql.NullString `json:"category"`
	Notes          sql.NullString `json:"notes"`
	UrlBidx        string         `json:"url_bidx"`
}

// ============================================================================
// Import - bulk insert (used inside transaction)
// ============================================================================
func (q *Queries) ImportVaultEntry(ctx context.Context, arg ImportVaultEntryParams) error {
	_, err := q.db.ExecContext(ctx, importVaultEntry,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedValue,
		arg.Nonce,
		arg.Url,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.UrlBidx,
	)
	return err
}

const listAllVaultEntries = `-- name: ListAllVaultEntries :many

SELECT id, user_id, name, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, last_rotated_at, provider, provider_meta, auto_rotate, last_rotation_error, created_at, updated_at
FROM vault_entries ORDER BY name ASC
`

type ListAllVaultEntriesRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// ============================================================================
// List entries (metadata only)
// ============================================================================
func (q *Queries) ListAllVaultEntries(ctx context.Context) ([]ListAllVaultEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllVaultEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllVaultEntriesRow{}
	for rows.Next() {
		var i ListAllVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderEntries = `-- name: ListProviderEntries :many
SELECT id, user_id, name, provider, provider_meta, auto_rotate, rotation_interval_days, expires_at, last_rotated_at, last_rotation_error, rotation_log, rotation_targets, created_at, updated_at
FROM vault_entries WHERE provider != '' ORDER BY provider ASC, name ASC
`

type ListProviderEntriesRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	RotationLog          sql.NullString `json:"rotation_log"`
	RotationTargets      sql.NullString `json:"rotation_targets"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListProviderEntries(ctx context.Context) ([]ListProviderEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderEntriesRow{}
	for rows.Next() {
		var i ListProviderEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.LastRotationError,
			&i.RotationLog,
			&i.RotationTargets,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesByUser = `-- name: ListVaultEntriesByUser :many
SELECT id, user_id, name, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, last_rotated_at, provider, provider_meta, auto_rotate, last_rotation_error, created_at, updated_at
FROM vault_entries WHERE user_id = ? ORDER BY name ASC
`

type ListVaultEntriesByUserRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListVaultEntriesByUser(ctx context.Context, userID string) ([]ListVaultEntriesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesByUserRow{}
	for rows.Next() {
		var i ListVaultEntriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesForMetaAtRestBackfill = `-- name: ListVaultEntriesForMetaAtRestBackfill :many

SELECT id, url, alias_url, username, category, notes, url_bidx, alias_url_bidx FROM vault_entries
`

type ListVaultEntriesForMetaAtRestBackfillRow struct {
	ID           string         `json:"id"`
	Url          sql.NullString `json:"url"`
	AliasUrl     sql.NullString `json:"alias_url"`
	Username     sql.NullString `json:"username"`
	Category     sql.NullString `json:"category"`
	Notes        sql.NullString `json:"notes"`
	UrlBidx      string         `json:"url_bidx"`
	AliasUrlBidx string         `json:"alias_url_bidx"`
}

// ============================================================================
// Metadata-at-rest backfill (encrypt url/alias_url/username/category/notes,
// compute url_bidx/alias_url_bidx). Runs once at boot via
// VaultHandler.BackfillMetadataAtRest; idempotent (enc:v1: prefix guards it).
// ============================================================================
func (q *Queries) ListVaultEntriesForMetaAtRestBackfill(ctx context.Context) ([]ListVaultEntriesForMetaAtRestBackfillRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesForMetaAtRestBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesForMetaAtRestBackfillRow{}
	for rows.Next() {
		var i ListVaultEntriesForMetaAtRestBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.UrlBidx,
			&i.AliasUrlBidx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesForMetaBackfill = `-- name: ListVaultEntriesForMetaBackfill :many
SELECT id, provider_meta, rotation_targets FROM vault_entries
`

type ListVaultEntriesForMetaBackfillRow struct {
	ID              string         `json:"id"`
	ProviderMeta    sql.NullString `json:"provider_meta"`
	RotationTargets sql.NullString `json:"rotation_targets"`
}

func (q *Queries) ListVaultEntriesForMetaBackfill(ctx context.Context) ([]ListVaultEntriesForMetaBackfillRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesForMetaBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesForMetaBackfillRow{}
	for rows.Next() {
		var i ListVaultEntriesForMetaBackfillRow
		if err := rows.Scan(&i.ID, &i.ProviderMeta, &i.RotationTargets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesNeedingRotation = `-- name: ListVaultEntriesNeedingRotation :many
SELECT id, user_id, name, encrypted_value, nonce, encryption_version, provider, provider_meta, rotation_interval_days, last_rotated_at, rotation_log, rotation_targets
FROM vault_entries
WHERE auto_rotate = 1
  AND provider != ''
  AND rotation_interval_days > 0
  AND (
    last_rotated_at IS NULL
    OR (julianday('now') - julianday(last_rotated_at)) >= rotation_interval_days
  )
ORDER BY last_rotated_at ASC
`

type ListVaultEntriesNeedingRotationRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Name                 string         `json:"name"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
	EncryptionVersion    sql.NullInt64  `json:"encryption_version"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	RotationLog          sql.NullString `json:"rotation_log"`
	RotationTargets      sql.NullString `json:"rotation_targets"`
}

func (q *Queries) ListVaultEntriesNeedingRotation(ctx context.Context) ([]ListVaultEntriesNeedingRotationRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesNeedingRotation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesNeedingRotationRow{}
	for rows.Next() {
		var i ListVaultEntriesNeedingRotationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.EncryptedValue,
			&i.Nonce,
			&i.EncryptionVersion,
			&i.Provider,
			&i.ProviderMeta,
			&i.RotationIntervalDays,
			&i.LastRotatedAt,
			&i.RotationLog,
			&i.RotationTargets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesV1 = `-- name: ListVaultEntriesV1 :many
SELECT id, encrypted_value, nonce FROM vault_entries WHERE encryption_version = 1
`

type ListVaultEntriesV1Row struct {
	ID             string `json:"id"`
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
}

func (q *Queries) ListVaultEntriesV1(ctx context.Context) ([]ListVaultEntriesV1Row, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesV1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesV1Row{}
	for rows.Next() {
		var i ListVaultEntriesV1Row
		if err := rows.Scan(&i.ID, &i.EncryptedValue, &i.Nonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntriesWithSecrets = `-- name: ListVaultEntriesWithSecrets :many
SELECT id, name, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, last_rotated_at, provider, provider_meta, auto_rotate, last_rotation_error, created_at, updated_at, encrypted_value, nonce
FROM vault_entries WHERE user_id = ? ORDER BY name ASC
`

type ListVaultEntriesWithSecretsRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	EncryptedValue       []byte         `json:"encrypted_value"`
	Nonce                []byte         `json:"nonce"`
}

func (q *Queries) ListVaultEntriesWithSecrets(ctx context.Context, userID string) ([]ListVaultEntriesWithSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntriesWithSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultEntriesWithSecretsRow{}
	for rows.Next() {
		var i ListVaultEntriesWithSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptedValue,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultEntryNamesByUser = `-- name: ListVaultEntryNamesByUser :many

SELECT name FROM vault_entries WHERE user_id = ?
`

// ============================================================================
// Import - conflict detection
// ============================================================================
func (q *Queries) ListVaultEntryNamesByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listVaultEntryNamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchVaultEntriesByURL = `-- name: MatchVaultEntriesByURL :many

SELECT id, name, url, alias_url, username, category, notes, auto_login, rotation_interval_days, expires_at, last_rotated_at, provider, provider_meta, auto_rotate, last_rotation_error, created_at, updated_at
FROM vault_entries WHERE user_id = ? AND ((url_bidx != '' AND url_bidx = ?) OR (alias_url_bidx != '' AND alias_url_bidx = ?)) ORDER BY name ASC
`

type MatchVaultEntriesByURLParams struct {
	UserID       string `json:"user_id"`
	UrlBidx      string `json:"url_bidx"`
	AliasUrlBidx string `json:"alias_url_bidx"`
}

type MatchVaultEntriesByURLRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Url                  sql.NullString `json:"url"`
	AliasUrl             sql.NullString `json:"alias_url"`
	Username             sql.NullString `json:"username"`
	Category             sql.NullString `json:"category"`
	Notes                sql.NullString `json:"notes"`
	AutoLogin            int64          `json:"auto_login"`
	RotationIntervalDays sql.NullInt64  `json:"rotation_interval_days"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	LastRotatedAt        sql.NullTime   `json:"last_rotated_at"`
	Provider             sql.NullString `json:"provider"`
	ProviderMeta         sql.NullString `json:"provider_meta"`
	AutoRotate           sql.NullInt64  `json:"auto_rotate"`
	LastRotationError    sql.NullString `json:"last_rotation_error"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// ============================================================================
// URL matching (browser extension autofill)
// ============================================================================
// Autofill lookup by blind index. url/alias_url are encrypted at rest and cannot
// be LIKE-matched, so the handler computes HMAC-SHA256(normalized_host) from the
// requested url (see vault.go urlBlindIndex) and matches it against the stored
// url_bidx / alias_url_bidx. Both bind params carry the SAME computed index.
func (q *Queries) MatchVaultEntriesByURL(ctx context.Context, arg MatchVaultEntriesByURLParams) ([]MatchVaultEntriesByURLRow, error) {
	rows, err := q.db.QueryContext(ctx, matchVaultEntriesByURL, arg.UserID, arg.UrlBidx, arg.AliasUrlBidx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchVaultEntriesByURLRow{}
	for rows.Next() {
		var i MatchVaultEntriesByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.AliasUrl,
			&i.Username,
			&i.Category,
			&i.Notes,
			&i.AutoLogin,
			&i.RotationIntervalDays,
			&i.ExpiresAt,
			&i.LastRotatedAt,
			&i.Provider,
			&i.ProviderMeta,
			&i.AutoRotate,
			&i.LastRotationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateVaultEntryEncryption = `-- name: MigrateVaultEntryEncryption :exec
UPDATE vault_entries SET encrypted_value = ?, nonce = ?, encryption_version = 2 WHERE id = ?
`

type MigrateVaultEntryEncryptionParams struct {
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
	ID             string `json:"id"`
}

func (q *Queries) MigrateVaultEntryEncryption(ctx context.Context, arg MigrateVaultEntryEncryptionParams) error {
	_, err := q.db.ExecContext(ctx, migrateVaultEntryEncryption, arg.EncryptedValue, arg.Nonce, arg.ID)
	return err
}

const resolveVaultReference = `-- name: ResolveVaultReference :one

SELECT encrypted_value, nonce FROM vault_entries
WHERE vault_entries.name = ? AND user_id = ?
`

type ResolveVaultReferenceParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

type ResolveVaultReferenceRow struct {
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
}

// ============================================================================
// Resolve {{vault:NAME}} references (scoped to requesting user's vault)
// ============================================================================
func (q *Queries) ResolveVaultReference(ctx context.Context, arg ResolveVaultReferenceParams) (ResolveVaultReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, resolveVaultReference, arg.Name, arg.UserID)
	var i ResolveVaultReferenceRow
	err := row.Scan(&i.EncryptedValue, &i.Nonce)
	return i, err
}

const rotateVaultEntryValue = `-- name: RotateVaultEntryValue :execresult

UPDATE vault_entries SET encrypted_value = ?, nonce = ?, encryption_version = 2, last_rotated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type RotateVaultEntryValueParams struct {
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
	ID             string `json:"id"`
}

// ============================================================================
// Rotate (generate new secret value)
// ============================================================================
func (q *Queries) RotateVaultEntryValue(ctx context.Context, arg RotateVaultEntryValueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rotateVaultEntryValue, arg.EncryptedValue, arg.Nonce, arg.ID)
}

const updateVaultEntryAliasURL = `-- name: UpdateVaultEntryAliasURL :exec
UPDATE vault_entries SET alias_url = ?, alias_url_bidx = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryAliasURLParams struct {
	AliasUrl     sql.NullString `json:"alias_url"`
	AliasUrlBidx string         `json:"alias_url_bidx"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryAliasURL(ctx context.Context, arg UpdateVaultEntryAliasURLParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryAliasURL, arg.AliasUrl, arg.AliasUrlBidx, arg.ID)
	return err
}

const updateVaultEntryAutoLogin = `-- name: UpdateVaultEntryAutoLogin :exec
UPDATE vault_entries SET auto_login = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryAutoLoginParams struct {
	AutoLogin int64  `json:"auto_login"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateVaultEntryAutoLogin(ctx context.Context, arg UpdateVaultEntryAutoLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryAutoLogin, arg.AutoLogin, arg.ID)
	return err
}

const updateVaultEntryCategory = `-- name: UpdateVaultEntryCategory :exec
UPDATE vault_entries SET category = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryCategoryParams struct {
	Category sql.NullString `json:"category"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryCategory(ctx context.Context, arg UpdateVaultEntryCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryCategory, arg.Category, arg.ID)
	return err
}

const updateVaultEntryExpiresAt = `-- name: UpdateVaultEntryExpiresAt :exec
UPDATE vault_entries SET expires_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryExpiresAtParams struct {
	ExpiresAt sql.NullTime `json:"expires_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateVaultEntryExpiresAt(ctx context.Context, arg UpdateVaultEntryExpiresAtParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryExpiresAt, arg.ExpiresAt, arg.ID)
	return err
}

const updateVaultEntryMetaAtRest = `-- name: UpdateVaultEntryMetaAtRest :exec
UPDATE vault_entries
SET url = ?, alias_url = ?, username = ?, category = ?, notes = ?, url_bidx = ?, alias_url_bidx = ?
WHERE id = ?
`

type UpdateVaultEntryMetaAtRestParams struct {
	Url          sql.NullString `json:"url"`
	AliasUrl     sql.NullString `json:"alias_url"`
	Username     sql.NullString `json:"username"`
	Category     sql.NullString `json:"category"`
	Notes        sql.NullString `json:"notes"`
	UrlBidx      string         `json:"url_bidx"`
	AliasUrlBidx string         `json:"alias_url_bidx"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryMetaAtRest(ctx context.Context, arg UpdateVaultEntryMetaAtRestParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryMetaAtRest,
		arg.Url,
		arg.AliasUrl,
		arg.Username,
		arg.Category,
		arg.Notes,
		arg.UrlBidx,
		arg.AliasUrlBidx,
		arg.ID,
	)
	return err
}

const updateVaultEntryName = `-- name: UpdateVaultEntryName :exec

UPDATE vault_entries SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

// ============================================================================
// Update entry - individual metadata fields
// ============================================================================
func (q *Queries) UpdateVaultEntryName(ctx context.Context, arg UpdateVaultEntryNameParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryName, arg.Name, arg.ID)
	return err
}

const updateVaultEntryNotes = `-- name: UpdateVaultEntryNotes :exec
UPDATE vault_entries SET notes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryNotesParams struct {
	Notes sql.NullString `json:"notes"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryNotes(ctx context.Context, arg UpdateVaultEntryNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryNotes, arg.Notes, arg.ID)
	return err
}

const updateVaultEntryProvider = `-- name: UpdateVaultEntryProvider :exec

UPDATE vault_entries SET provider = ?, provider_meta = ?, auto_rotate = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderParams struct {
	Provider     sql.NullString `json:"provider"`
	ProviderMeta sql.NullString `json:"provider_meta"`
	AutoRotate   sql.NullInt64  `json:"auto_rotate"`
	ID           string         `json:"id"`
}

// ============================================================================
// Provider integration (API key rotation)
// ============================================================================
func (q *Queries) UpdateVaultEntryProvider(ctx context.Context, arg UpdateVaultEntryProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProvider,
		arg.Provider,
		arg.ProviderMeta,
		arg.AutoRotate,
		arg.ID,
	)
	return err
}

const updateVaultEntryProviderMeta = `-- name: UpdateVaultEntryProviderMeta :exec
UPDATE vault_entries SET provider_meta = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryProviderMetaParams struct {
	ProviderMeta sql.NullString `json:"provider_meta"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryProviderMeta(ctx context.Context, arg UpdateVaultEntryProviderMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryProviderMeta, arg.ProviderMeta, arg.ID)
	return err
}

const updateVaultEntryRotationError = `-- name: UpdateVaultEntryRotationError :exec
UPDATE vault_entries SET last_rotation_error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationErrorParams struct {
	LastRotationError sql.NullString `json:"last_rotation_error"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationError(ctx context.Context, arg UpdateVaultEntryRotationErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationError, arg.LastRotationError, arg.ID)
	return err
}

const updateVaultEntryRotationInterval = `-- name: UpdateVaultEntryRotationInterval :exec
UPDATE vault_entries SET rotation_interval_days = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationIntervalParams struct {
	RotationIntervalDays sql.NullInt64 `json:"rotation_interval_days"`
	ID                   string        `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationInterval(ctx context.Context, arg UpdateVaultEntryRotationIntervalParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationInterval, arg.RotationIntervalDays, arg.ID)
	return err
}

const updateVaultEntryRotationLog = `-- name: UpdateVaultEntryRotationLog :exec
UPDATE vault_entries SET rotation_log = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationLogParams struct {
	RotationLog sql.NullString `json:"rotation_log"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationLog(ctx context.Context, arg UpdateVaultEntryRotationLogParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationLog, arg.RotationLog, arg.ID)
	return err
}

const updateVaultEntryRotationTargets = `-- name: UpdateVaultEntryRotationTargets :exec
UPDATE vault_entries SET rotation_targets = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryRotationTargetsParams struct {
	RotationTargets sql.NullString `json:"rotation_targets"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryRotationTargets(ctx context.Context, arg UpdateVaultEntryRotationTargetsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryRotationTargets, arg.RotationTargets, arg.ID)
	return err
}

const updateVaultEntryURL = `-- name: UpdateVaultEntryURL :exec
UPDATE vault_entries SET url = ?, url_bidx = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryURLParams struct {
	Url     sql.NullString `json:"url"`
	UrlBidx string         `json:"url_bidx"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryURL(ctx context.Context, arg UpdateVaultEntryURLParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryURL, arg.Url, arg.UrlBidx, arg.ID)
	return err
}

const updateVaultEntryUsername = `-- name: UpdateVaultEntryUsername :exec
UPDATE vault_entries SET username = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryUsernameParams struct {
	Username sql.NullString `json:"username"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateVaultEntryUsername(ctx context.Context, arg UpdateVaultEntryUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryUsername, arg.Username, arg.ID)
	return err
}

const updateVaultEntryValue = `-- name: UpdateVaultEntryValue :exec

UPDATE vault_entries SET encrypted_value = ?, nonce = ?, encryption_version = 2, last_rotated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVaultEntryValueParams struct {
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
	ID             string `json:"id"`
}

// ============================================================================
// Update entry - encrypted value (re-encrypt + rotate timestamp)
// ============================================================================
func (q *Queries) UpdateVaultEntryValue(ctx context.Context, arg UpdateVaultEntryValueParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultEntryValue, arg.EncryptedValue, arg.Nonce, arg.ID)
	return err
}
